skipR [(const,left:(0, 0),right:(0, 0)), (linear,right(1),right:(0, 0))]
skipL [(linear,right(1),right:(0, 0)), (linear,right(1),right:(0, 0))]
alignment [(linear,right(1),right:(0, 0)), (linear,right(1),right:(0, 0))]
xDel [(linear,right(1),right:(0, 0)), (linear,right(1),right:(0, 0))]
xIns [(linear,right(1),right:(0, 0)), (linear,right(1),right:(0, 0))]
