digraph readStructure {
compound = True;
newrank=True;
ordering=out;
subgraph cluster_readStructure{
node_1 [ label=<<table border='0'><tr><td>struct</td></tr></table>>, color="black", shape="box", penwidth=3 ];
node_2 [ label=<<table border='0'><tr><td>sadd</td></tr></table>>, color="green" ];
node_3 [ label=<<table border='0'><tr><td>CHAR('.')</td></tr></table>>, color="blue" ];
node_2 -> node_3 [ arrowhead=none ];
node_4 [ label=<<table border='0'><tr><td>struct</td></tr></table>>, color="black" ];
node_2 -> node_4 [ arrowhead=none ];
node_1_2[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_1 -> node_1_2[style= invis, weight=99];
node_1_2 -> node_2[style= invis];
node_5 [ label=<<table border='0'><tr><td>cadd</td></tr></table>>, color="green" ];
node_6 [ label=<<table border='0'><tr><td>closed</td></tr></table>>, color="black" ];
node_5 -> node_6 [ arrowhead=none ];
node_7 [ label=<<table border='0'><tr><td>struct</td></tr></table>>, color="black" ];
node_5 -> node_7 [ arrowhead=none ];
node_2_5[ label=<<table border='0'><tr><td><font point-size='30'>|</font></td></tr></table>>, shape=plaintext];
node_2 -> node_2_5[style= invis];
node_2_5 -> node_5[style= invis];
node_8 [ label=<<table border='0'><tr><td>nil</td></tr></table>>, color="green" ];
node_9 [ label=<<table border='0'><tr><td>EMPTY</td></tr></table>>, color="blue" ];
node_8 -> node_9 [ arrowhead=none ];
node_5_8[ label=<<table border='0'><tr><td><font point-size='30'>|</font></td></tr></table>>, shape=plaintext];
node_5 -> node_5_8[style= invis];
node_5_8 -> node_8[style= invis];
node_10 [ label=h, fontcolor="purple" , shape=none ];
node_1 -> node_10 [ arrowhead=none, color="purple" , weight=99];
node_11[label = struct, shape="box", style=invis];
node_10 -> node_11[weight = 99, style = invis];
node_12[label = struct, shape="box", style=invis];
node_11 -> node_12[weight = 99, style = invis];
{ rank=same node_1 node_1_2 node_2 node_2_5 node_5 node_5_8 node_8 }
}
subgraph cluster_readStructure{
node_13 [ label=<<table border='0'><tr><td>closed</td></tr></table>>, color="black", shape="box" ];
node_14 [ label=<<table border='0'><tr><td>hairpin</td></tr></table>>, color="green" ];
node_15 [ label=<<table border='0'><tr><td>CHAR('(')</td></tr></table>>, color="blue" ];
node_14 -> node_15 [ arrowhead=none ];
node_16 [ label=<<table border='0'><tr><td>CHAR('(')</td></tr></table>>, color="blue" ];
node_14 -> node_16 [ arrowhead=none ];
node_17 [ label=<<table border='0'><tr><td>REGION</td></tr></table>>, color="blue" ];
node_18 [ label="minsize(3)" , fontcolor="magenta" , shape=none ];
node_17 -> node_18 [ arrowhead=none, color="magenta" ];
node_19 [ label="onlychar('.')" , fontcolor="magenta" , shape=none ];
node_17 -> node_19 [ arrowhead=none, color="magenta" ];
node_14 -> node_17 [ arrowhead=none ];
node_20 [ label=<<table border='0'><tr><td>CHAR(')')</td></tr></table>>, color="blue" ];
node_14 -> node_20 [ arrowhead=none ];
node_21 [ label=<<table border='0'><tr><td>CHAR(')')</td></tr></table>>, color="blue" ];
node_14 -> node_21 [ arrowhead=none ];
node_13_14[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_13 -> node_13_14[style= invis, weight=99];
node_13_14 -> node_14[style= invis];
node_22 [ label=<<table border='0'><tr><td>stack</td></tr></table>>, color="green" ];
node_23 [ label=<<table border='0'><tr><td>CHAR('(')</td></tr></table>>, color="blue" ];
node_22 -> node_23 [ arrowhead=none ];
node_24 [ label=<<table border='0'><tr><td>closed</td></tr></table>>, color="black" ];
node_22 -> node_24 [ arrowhead=none ];
node_25 [ label=<<table border='0'><tr><td>CHAR(')')</td></tr></table>>, color="blue" ];
node_22 -> node_25 [ arrowhead=none ];
node_14_22[ label=<<table border='0'><tr><td><font point-size='30'>|</font></td></tr></table>>, shape=plaintext];
node_14 -> node_14_22[style= invis];
node_14_22 -> node_22[style= invis];
node_26 [ label=<<table border='0'><tr><td>bulgeleft</td></tr></table>>, color="green" ];
node_27 [ label=<<table border='0'><tr><td>CHAR('(')</td></tr></table>>, color="blue" ];
node_26 -> node_27 [ arrowhead=none ];
node_28 [ label=<<table border='0'><tr><td>CHAR('(')</td></tr></table>>, color="blue" ];
node_26 -> node_28 [ arrowhead=none ];
node_29 [ label=<<table border='0'><tr><td>REGION</td></tr></table>>, color="blue" ];
node_30 [ label="onlychar('.')" , fontcolor="magenta" , shape=none ];
node_29 -> node_30 [ arrowhead=none, color="magenta" ];
node_26 -> node_29 [ arrowhead=none ];
node_31 [ label=<<table border='0'><tr><td>closed</td></tr></table>>, color="black" ];
node_26 -> node_31 [ arrowhead=none ];
node_32 [ label=<<table border='0'><tr><td>CHAR(')')</td></tr></table>>, color="blue" ];
node_26 -> node_32 [ arrowhead=none ];
node_33 [ label=<<table border='0'><tr><td>CHAR(')')</td></tr></table>>, color="blue" ];
node_26 -> node_33 [ arrowhead=none ];
node_22_26[ label=<<table border='0'><tr><td><font point-size='30'>|</font></td></tr></table>>, shape=plaintext];
node_22 -> node_22_26[style= invis];
node_22_26 -> node_26[style= invis];
node_34 [ label=<<table border='0'><tr><td>bulgeright</td></tr></table>>, color="green" ];
node_35 [ label=<<table border='0'><tr><td>CHAR('(')</td></tr></table>>, color="blue" ];
node_34 -> node_35 [ arrowhead=none ];
node_36 [ label=<<table border='0'><tr><td>CHAR('(')</td></tr></table>>, color="blue" ];
node_34 -> node_36 [ arrowhead=none ];
node_37 [ label=<<table border='0'><tr><td>closed</td></tr></table>>, color="black" ];
node_34 -> node_37 [ arrowhead=none ];
node_38 [ label=<<table border='0'><tr><td>REGION</td></tr></table>>, color="blue" ];
node_39 [ label="onlychar('.')" , fontcolor="magenta" , shape=none ];
node_38 -> node_39 [ arrowhead=none, color="magenta" ];
node_34 -> node_38 [ arrowhead=none ];
node_40 [ label=<<table border='0'><tr><td>CHAR(')')</td></tr></table>>, color="blue" ];
node_34 -> node_40 [ arrowhead=none ];
node_41 [ label=<<table border='0'><tr><td>CHAR(')')</td></tr></table>>, color="blue" ];
node_34 -> node_41 [ arrowhead=none ];
node_26_34[ label=<<table border='0'><tr><td><font point-size='30'>|</font></td></tr></table>>, shape=plaintext];
node_26 -> node_26_34[style= invis];
node_26_34 -> node_34[style= invis];
node_42 [ label=<<table border='0'><tr><td>iloop</td></tr></table>>, color="green" ];
node_43 [ label=<<table border='0'><tr><td>CHAR('(')</td></tr></table>>, color="blue" ];
node_42 -> node_43 [ arrowhead=none ];
node_44 [ label=<<table border='0'><tr><td>CHAR('(')</td></tr></table>>, color="blue" ];
node_42 -> node_44 [ arrowhead=none ];
node_45 [ label=<<table border='0'><tr><td>REGION</td></tr></table>>, color="blue" ];
node_46 [ label="maxsize(30)" , fontcolor="magenta" , shape=none ];
node_45 -> node_46 [ arrowhead=none, color="magenta" ];
node_47 [ label="onlychar('.')" , fontcolor="magenta" , shape=none ];
node_45 -> node_47 [ arrowhead=none, color="magenta" ];
node_42 -> node_45 [ arrowhead=none ];
node_48 [ label=<<table border='0'><tr><td>closed</td></tr></table>>, color="black" ];
node_42 -> node_48 [ arrowhead=none ];
node_49 [ label=<<table border='0'><tr><td>REGION</td></tr></table>>, color="blue" ];
node_50 [ label="maxsize(30)" , fontcolor="magenta" , shape=none ];
node_49 -> node_50 [ arrowhead=none, color="magenta" ];
node_51 [ label="onlychar('.')" , fontcolor="magenta" , shape=none ];
node_49 -> node_51 [ arrowhead=none, color="magenta" ];
node_42 -> node_49 [ arrowhead=none ];
node_52 [ label=<<table border='0'><tr><td>CHAR(')')</td></tr></table>>, color="blue" ];
node_42 -> node_52 [ arrowhead=none ];
node_53 [ label=<<table border='0'><tr><td>CHAR(')')</td></tr></table>>, color="blue" ];
node_42 -> node_53 [ arrowhead=none ];
node_34_42[ label=<<table border='0'><tr><td><font point-size='30'>|</font></td></tr></table>>, shape=plaintext];
node_34 -> node_34_42[style= invis];
node_34_42 -> node_42[style= invis];
node_54 [ label=<<table border='0'><tr><td>multiloop</td></tr></table>>, color="green" ];
node_55 [ label=<<table border='0'><tr><td>CHAR('(')</td></tr></table>>, color="blue" ];
node_54 -> node_55 [ arrowhead=none ];
node_56 [ label=<<table border='0'><tr><td>CHAR('(')</td></tr></table>>, color="blue" ];
node_54 -> node_56 [ arrowhead=none ];
node_57 [ label=<<table border='0'><tr><td>ml_components</td></tr></table>>, color="black" ];
node_54 -> node_57 [ arrowhead=none ];
node_58 [ label=<<table border='0'><tr><td>CHAR(')')</td></tr></table>>, color="blue" ];
node_54 -> node_58 [ arrowhead=none ];
node_59 [ label=<<table border='0'><tr><td>CHAR(')')</td></tr></table>>, color="blue" ];
node_54 -> node_59 [ arrowhead=none ];
node_42_54[ label=<<table border='0'><tr><td><font point-size='30'>|</font></td></tr></table>>, shape=plaintext];
node_42 -> node_42_54[style= invis];
node_42_54 -> node_54[style= invis];
node_60 [ label=h, fontcolor="purple" , shape=none ];
node_13 -> node_60 [ arrowhead=none, color="purple" , weight=99];
node_61[label = closed, shape="box", style=invis];
node_60 -> node_61[weight = 99, style = invis];
node_62[label = closed, shape="box", style=invis];
node_61 -> node_62[weight = 99, style = invis];
{ rank=same node_13 node_13_14 node_14 node_14_22 node_22 node_22_26 node_26 node_26_34 node_34 node_34_42 node_42 node_42_54 node_54 }
}
node_12 -> node_13 [ style = invis];
subgraph cluster_readStructure{
node_63 [ label=<<table border='0'><tr><td>ml_components</td></tr></table>>, color="black", shape="box", style="dotted" ];
node_64 [ label=<<table border='0'><tr><td>combine</td></tr></table>>, color="green" ];
node_65 [ label=<<table border='0'><tr><td>block</td></tr></table>>, color="black" ];
node_64 -> node_65 [ arrowhead=none ];
node_66 [ label=<<table border='0'><tr><td>comps</td></tr></table>>, color="black" ];
node_64 -> node_66 [ arrowhead=none ];
node_63_64[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_63 -> node_63_64[style= invis, weight=99];
node_63_64 -> node_64[style= invis];
node_67 [ label=h, fontcolor="purple" , shape=none ];
node_63 -> node_67 [ arrowhead=none, color="purple" , weight=99];
node_68[label = ml_components, shape="box", style=invis];
node_67 -> node_68[weight = 99, style = invis];
{ rank=same node_63 node_63_64 node_64 }
}
node_62 -> node_63 [ style = invis];
subgraph cluster_readStructure{
node_69 [ label=<<table border='0'><tr><td>block</td></tr></table>>, color="black", shape="box" ];
node_70 [ label=<<table border='0'><tr><td>closed</td></tr></table>>, color="black" ];
node_69_70[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_69 -> node_69_70[style= invis, weight=99];
node_69_70 -> node_70[style= invis];
node_71 [ label=<<table border='0'><tr><td>ssadd</td></tr></table>>, color="green" ];
node_72 [ label=<<table border='0'><tr><td>REGION</td></tr></table>>, color="blue" ];
node_73 [ label="onlychar('.')" , fontcolor="magenta" , shape=none ];
node_72 -> node_73 [ arrowhead=none, color="magenta" ];
node_71 -> node_72 [ arrowhead=none ];
node_74 [ label=<<table border='0'><tr><td>closed</td></tr></table>>, color="black" ];
node_71 -> node_74 [ arrowhead=none ];
node_70_71[ label=<<table border='0'><tr><td><font point-size='30'>|</font></td></tr></table>>, shape=plaintext];
node_70 -> node_70_71[style= invis];
node_70_71 -> node_71[style= invis];
node_75 [ label=h, fontcolor="purple" , shape=none ];
node_69 -> node_75 [ arrowhead=none, color="purple" , weight=99];
node_76[label = block, shape="box", style=invis];
node_75 -> node_76[weight = 99, style = invis];
{ rank=same node_69 node_69_70 node_70 node_70_71 node_71 }
}
node_68 -> node_69 [ style = invis];
subgraph cluster_readStructure{
node_77 [ label=<<table border='0'><tr><td>comps</td></tr></table>>, color="black", shape="box" ];
node_78 [ label=<<table border='0'><tr><td>combine</td></tr></table>>, color="green" ];
node_79 [ label=<<table border='0'><tr><td>block</td></tr></table>>, color="black" ];
node_78 -> node_79 [ arrowhead=none ];
node_80 [ label=<<table border='0'><tr><td>comps</td></tr></table>>, color="black" ];
node_78 -> node_80 [ arrowhead=none ];
node_77_78[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_77 -> node_77_78[style= invis, weight=99];
node_77_78 -> node_78[style= invis];
node_81 [ label=<<table border='0'><tr><td>block</td></tr></table>>, color="black" ];
node_78_81[ label=<<table border='0'><tr><td><font point-size='30'>|</font></td></tr></table>>, shape=plaintext];
node_78 -> node_78_81[style= invis];
node_78_81 -> node_81[style= invis];
node_82 [ label=<<table border='0'><tr><td>addss</td></tr></table>>, color="green" ];
node_83 [ label=<<table border='0'><tr><td>block</td></tr></table>>, color="black" ];
node_82 -> node_83 [ arrowhead=none ];
node_84 [ label=<<table border='0'><tr><td>REGION</td></tr></table>>, color="blue" ];
node_85 [ label="onlychar('.')" , fontcolor="magenta" , shape=none ];
node_84 -> node_85 [ arrowhead=none, color="magenta" ];
node_82 -> node_84 [ arrowhead=none ];
node_81_82[ label=<<table border='0'><tr><td><font point-size='30'>|</font></td></tr></table>>, shape=plaintext];
node_81 -> node_81_82[style= invis];
node_81_82 -> node_82[style= invis];
node_86 [ label=h, fontcolor="purple" , shape=none ];
node_77 -> node_86 [ arrowhead=none, color="purple" , weight=99];
node_87[label = comps, shape="box", style=invis];
node_86 -> node_87[weight = 99, style = invis];
{ rank=same node_77 node_77_78 node_78 node_78_81 node_81 node_81_82 node_82 }
}
node_76 -> node_77 [ style = invis];
}
