digraph tdm {
compound = True;
newrank = True;
ordering = out;
subgraph cluster_1 {
    node_1 [ label=<<table border='0'><tr><td>rnastruct</td></tr></table>>, color="black", shape="box", penwidth=3 ];
    node_1 -> node_2 [ style=invis, weight=99 ];
    node_2 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_2 -> node_3 [ style=invis ];
    node_3 [ label=<<table border='0'><tr><td>sadd</td></tr></table>>, color="green" ];
    node_4 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_3 -> node_4 [ arrowhead=none ];
    node_5 [ label=<<table border='0'><tr><td>rnastruct</td></tr></table>>, color="black" ];
    node_3 -> node_5 [ arrowhead=none ];
    node_3 -> node_6 [ style=invis ];
    node_6 [ label=<<table border='0'><tr><td><font point-size='30'>|</font></td></tr></table>>, shape=plaintext ];
    node_6 -> node_7 [ style=invis ];
    node_7 [ label=<<table border='0'><tr><td>addss</td></tr></table>>, color="green" ];
    node_8 [ label=<<table border='0'><tr><td>structstart</td></tr></table>>, color="black" ];
    node_7 -> node_8 [ arrowhead=none ];
    node_9 [ label=<<table border='0'><tr><td>UREGION</td></tr></table>>, color="blue" ];
    node_7 -> node_9 [ arrowhead=none ];
    node_10 [ label=h, fontcolor="purple", shape=none ];
    node_1 -> node_10 [ arrowhead=none, color="purple", weight=99 ];
    { rank=same node_1 node_2 node_3 node_6 node_7 }
}
node_10 -> node_11 [ style=invis ];
subgraph cluster_2 {
    node_11 [ label=<<table border='0'><tr><td>structstart</td></tr></table>>, color="black", shape="box" ];
    node_11 -> node_12 [ style=invis, weight=99 ];
    node_12 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_12 -> node_13 [ style=invis ];
    node_13 [ label=<<table border='0'><tr><td>cadd</td></tr></table>>, color="green" ];
    node_14 [ label=<<table border='0'><tr><td>motif0</td></tr></table>>, color="black" ];
    node_13 -> node_14 [ arrowhead=none ];
    node_15 [ label=<<table border='0'><tr><td>tail0</td></tr></table>>, color="black" ];
    node_13 -> node_15 [ arrowhead=none ];
    node_16 [ label=h, fontcolor="purple", shape=none ];
    node_11 -> node_16 [ arrowhead=none, color="purple", weight=99 ];
    { rank=same node_11 node_12 node_13 }
}
node_16 -> node_17 [ style=invis ];
subgraph cluster_3 {
    node_17 [ label=<<table border='0'><tr><td>motif0</td></tr></table>>, color="black", shape="box" ];
    node_17 -> node_18 [ style=invis, weight=99 ];
    node_18 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_18 -> node_19 [ style=invis ];
    node_19 [ label=<<table border='0'><tr><td>dlr</td></tr></table>>, color="green" ];
    node_20 [ label=<<table border='0'><tr><td>LOC</td></tr></table>>, color="blue" ];
    node_19 -> node_20 [ arrowhead=none ];
    node_21 [ label=<<table border='0'><tr><td>stem0</td></tr></table>>, color="black" ];
    node_19 -> node_21 [ arrowhead=none ];
    node_22 [ label=<<table border='0'><tr><td>LOC</td></tr></table>>, color="blue" ];
    node_19 -> node_22 [ arrowhead=none ];
    node_23 [ label=h, fontcolor="purple", shape=none ];
    node_17 -> node_23 [ arrowhead=none, color="purple", weight=99 ];
    { rank=same node_17 node_18 node_19 }
}
node_23 -> node_24 [ style=invis ];
subgraph cluster_4 {
    node_24 [ label=<<table border='0'><tr><td>stem0</td></tr></table>>, color="black", shape="box", style="dotted" ];
    node_24 -> node_25 [ style=invis, weight=99 ];
    node_25 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_25 -> node_26 [ style=invis ];
    node_26 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_27 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_26 -> node_27 [ arrowhead=none, color="magenta" ];
    node_28 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_26 -> node_28 [ arrowhead=none ];
    node_29 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_30 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_29 -> node_30 [ arrowhead=none, color="magenta" ];
    node_31 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_29 -> node_31 [ arrowhead=none ];
    node_32 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_33 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_32 -> node_33 [ arrowhead=none, color="magenta" ];
    node_34 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_32 -> node_34 [ arrowhead=none ];
    node_35 [ label=<<table border='0'><tr><td>maxstem0</td></tr></table>>, color="black" ];
    node_32 -> node_35 [ arrowhead=none ];
    node_36 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_32 -> node_36 [ arrowhead=none ];
    node_29 -> node_32 [ arrowhead=none ];
    node_37 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_29 -> node_37 [ arrowhead=none ];
    node_26 -> node_29 [ arrowhead=none ];
    node_38 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_26 -> node_38 [ arrowhead=none ];
    node_39 [ label=h, fontcolor="purple", shape=none ];
    node_24 -> node_39 [ arrowhead=none, color="purple", weight=99 ];
    node_39 -> node_40 [ style=invis, weight=99 ];
    node_40 [ style=invis ];
    node_40 -> node_41 [ style=invis, weight=99 ];
    node_41 [ style=invis ];
    { rank=same node_24 node_25 node_26 }
}
node_41 -> node_42 [ style=invis ];
subgraph cluster_5 {
    node_42 [ label=<<table border='0'><tr><td>maxstem0</td></tr></table>>, color="black", shape="box", style="dotted" ];
    node_42 -> node_43 [ style=invis, weight=99 ];
    node_43 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_43 -> node_44 [ style=invis ];
    node_44 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_45 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_44 -> node_45 [ arrowhead=none, color="magenta" ];
    node_46 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_44 -> node_46 [ arrowhead=none ];
    node_47 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_48 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black" ];
    node_47 -> node_48 [ ];
    node_49 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_50 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_49 -> node_50 [ arrowhead=none, color="magenta" ];
    node_51 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_49 -> node_51 [ arrowhead=none ];
    node_52 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_53 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black" ];
    node_52 -> node_53 [ ];
    node_54 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_55 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_54 -> node_55 [ arrowhead=none, color="magenta" ];
    node_56 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_54 -> node_56 [ arrowhead=none ];
    node_57 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_58 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black" ];
    node_57 -> node_58 [ ];
    node_59 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_60 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_59 -> node_60 [ arrowhead=none, color="magenta" ];
    node_61 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_59 -> node_61 [ arrowhead=none ];
    node_62 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_63 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black" ];
    node_62 -> node_63 [ ];
    node_64 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_65 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_64 -> node_65 [ arrowhead=none, color="magenta" ];
    node_66 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_64 -> node_66 [ arrowhead=none ];
    node_67 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_68 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black" ];
    node_67 -> node_68 [ ];
    node_69 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_70 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_69 -> node_70 [ arrowhead=none, color="magenta" ];
    node_71 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_69 -> node_71 [ arrowhead=none ];
    node_72 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_73 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black" ];
    node_72 -> node_73 [ ];
    node_74 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_75 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_74 -> node_75 [ arrowhead=none, color="magenta" ];
    node_76 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_74 -> node_76 [ arrowhead=none ];
    node_77 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_78 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black" ];
    node_77 -> node_78 [ ];
    node_79 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_80 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_79 -> node_80 [ arrowhead=none, color="magenta" ];
    node_81 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_79 -> node_81 [ arrowhead=none ];
    node_82 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_83 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black" ];
    node_82 -> node_83 [ ];
    node_84 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_85 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_84 -> node_85 [ arrowhead=none, color="magenta" ];
    node_86 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_84 -> node_86 [ arrowhead=none ];
    node_87 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_88 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black" ];
    node_87 -> node_88 [ ];
    node_89 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_90 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_89 -> node_90 [ arrowhead=none, color="magenta" ];
    node_91 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_89 -> node_91 [ arrowhead=none ];
    node_92 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_93 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black" ];
    node_92 -> node_93 [ ];
    node_94 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_95 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_94 -> node_95 [ arrowhead=none, color="magenta" ];
    node_96 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_94 -> node_96 [ arrowhead=none ];
    node_97 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black" ];
    node_94 -> node_97 [ arrowhead=none ];
    node_98 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_94 -> node_98 [ arrowhead=none ];
    node_92 -> node_94 [ ];
    node_89 -> node_92 [ arrowhead=none ];
    node_99 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_89 -> node_99 [ arrowhead=none ];
    node_87 -> node_89 [ ];
    node_84 -> node_87 [ arrowhead=none ];
    node_100 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_84 -> node_100 [ arrowhead=none ];
    node_82 -> node_84 [ ];
    node_79 -> node_82 [ arrowhead=none ];
    node_101 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_79 -> node_101 [ arrowhead=none ];
    node_77 -> node_79 [ ];
    node_74 -> node_77 [ arrowhead=none ];
    node_102 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_74 -> node_102 [ arrowhead=none ];
    node_72 -> node_74 [ ];
    node_69 -> node_72 [ arrowhead=none ];
    node_103 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_69 -> node_103 [ arrowhead=none ];
    node_67 -> node_69 [ ];
    node_64 -> node_67 [ arrowhead=none ];
    node_104 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_64 -> node_104 [ arrowhead=none ];
    node_62 -> node_64 [ ];
    node_59 -> node_62 [ arrowhead=none ];
    node_105 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_59 -> node_105 [ arrowhead=none ];
    node_57 -> node_59 [ ];
    node_54 -> node_57 [ arrowhead=none ];
    node_106 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_54 -> node_106 [ arrowhead=none ];
    node_52 -> node_54 [ ];
    node_49 -> node_52 [ arrowhead=none ];
    node_107 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_49 -> node_107 [ arrowhead=none ];
    node_47 -> node_49 [ ];
    node_44 -> node_47 [ arrowhead=none ];
    node_108 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_44 -> node_108 [ arrowhead=none ];
    node_109 [ label=h, fontcolor="purple", shape=none ];
    node_42 -> node_109 [ arrowhead=none, color="purple", weight=99 ];
    node_109 -> node_110 [ style=invis, weight=99 ];
    node_110 [ style=invis ];
    node_110 -> node_111 [ style=invis, weight=99 ];
    node_111 [ style=invis ];
    node_111 -> node_112 [ style=invis, weight=99 ];
    node_112 [ style=invis ];
    node_112 -> node_113 [ style=invis, weight=99 ];
    node_113 [ style=invis ];
    node_113 -> node_114 [ style=invis, weight=99 ];
    node_114 [ style=invis ];
    node_114 -> node_115 [ style=invis, weight=99 ];
    node_115 [ style=invis ];
    node_115 -> node_116 [ style=invis, weight=99 ];
    node_116 [ style=invis ];
    node_116 -> node_117 [ style=invis, weight=99 ];
    node_117 [ style=invis ];
    node_117 -> node_118 [ style=invis, weight=99 ];
    node_118 [ style=invis ];
    node_118 -> node_119 [ style=invis, weight=99 ];
    node_119 [ style=invis ];
    node_119 -> node_120 [ style=invis, weight=99 ];
    node_120 [ style=invis ];
    node_120 -> node_121 [ style=invis, weight=99 ];
    node_121 [ style=invis ];
    node_121 -> node_122 [ style=invis, weight=99 ];
    node_122 [ style=invis ];
    node_122 -> node_123 [ style=invis, weight=99 ];
    node_123 [ style=invis ];
    node_123 -> node_124 [ style=invis, weight=99 ];
    node_124 [ style=invis ];
    node_124 -> node_125 [ style=invis, weight=99 ];
    node_125 [ style=invis ];
    node_125 -> node_126 [ style=invis, weight=99 ];
    node_126 [ style=invis ];
    node_126 -> node_127 [ style=invis, weight=99 ];
    node_127 [ style=invis ];
    node_127 -> node_128 [ style=invis, weight=99 ];
    node_128 [ style=invis ];
    node_128 -> node_129 [ style=invis, weight=99 ];
    node_129 [ style=invis ];
    { rank=same node_42 node_43 node_44 }
}
node_129 -> node_130 [ style=invis ];
subgraph cluster_6 {
    node_130 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black", shape="box", style="dotted" ];
    node_130 -> node_131 [ style=invis, weight=99 ];
    node_131 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_131 -> node_132 [ style=invis ];
    node_132 [ label=<<table border='0'><tr><td>hairpin1</td></tr></table>>, color="black" ];
    node_133 [ label=h, fontcolor="purple", shape=none ];
    node_130 -> node_133 [ arrowhead=none, color="purple", weight=99 ];
    { rank=same node_130 node_131 node_132 }
}
node_133 -> node_134 [ style=invis ];
subgraph cluster_7 {
    node_134 [ label=<<table border='0'><tr><td>hairpin1</td></tr></table>>, color="black", shape="box", style="dotted" ];
    node_134 -> node_135 [ style=invis, weight=99 ];
    node_135 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_135 -> node_136 [ style=invis ];
    node_136 [ label=<<table border='0'><tr><td>hl</td></tr></table>>, color="green" ];
    node_137 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_136 -> node_137 [ arrowhead=none, color="magenta" ];
    node_138 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_136 -> node_138 [ arrowhead=none ];
    node_139 [ label=<<table border='0'><tr><td>REGION</td></tr></table>>, color="blue" ];
    node_140 [ label="minsize(3)" , fontcolor="magenta" , shape=none ];
    node_139 -> node_140 [ arrowhead=none, color="magenta" ];
    node_136 -> node_139 [ arrowhead=none ];
    node_141 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_136 -> node_141 [ arrowhead=none ];
    node_142 [ label=h, fontcolor="purple", shape=none ];
    node_134 -> node_142 [ arrowhead=none, color="purple", weight=99 ];
    node_142 -> node_143 [ style=invis, weight=99 ];
    node_143 [ style=invis ];
    { rank=same node_134 node_135 node_136 }
}
node_143 -> node_144 [ style=invis ];
subgraph cluster_8 {
    node_144 [ label=<<table border='0'><tr><td>tail0</td></tr></table>>, color="black", shape="box" ];
    node_144 -> node_145 [ style=invis, weight=99 ];
    node_145 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_145 -> node_146 [ style=invis ];
    node_146 [ label=<<table border='0'><tr><td>cadd</td></tr></table>>, color="green" ];
    node_147 [ label=<<table border='0'><tr><td>motif2</td></tr></table>>, color="black" ];
    node_146 -> node_147 [ arrowhead=none ];
    node_148 [ label=<<table border='0'><tr><td>tail1</td></tr></table>>, color="black" ];
    node_146 -> node_148 [ arrowhead=none ];
    node_149 [ label=h, fontcolor="purple", shape=none ];
    node_144 -> node_149 [ arrowhead=none, color="purple", weight=99 ];
    { rank=same node_144 node_145 node_146 }
}
node_149 -> node_150 [ style=invis ];
subgraph cluster_9 {
    node_150 [ label=<<table border='0'><tr><td>motif2</td></tr></table>>, color="black", shape="box", style="dotted" ];
    node_150 -> node_151 [ style=invis, weight=99 ];
    node_151 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_151 -> node_152 [ style=invis ];
    node_152 [ label=<<table border='0'><tr><td>ss</td></tr></table>>, color="green" ];
    node_153 [ label=<<table border='0'><tr><td>UREGION</td></tr></table>>, color="blue" ];
    node_152 -> node_153 [ arrowhead=none ];
    node_154 [ label=h, fontcolor="purple", shape=none ];
    node_150 -> node_154 [ arrowhead=none, color="purple", weight=99 ];
    { rank=same node_150 node_151 node_152 }
}
node_154 -> node_155 [ style=invis ];
subgraph cluster_10 {
    node_155 [ label=<<table border='0'><tr><td>tail1</td></tr></table>>, color="black", shape="box" ];
    node_155 -> node_156 [ style=invis, weight=99 ];
    node_156 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_156 -> node_157 [ style=invis ];
    node_157 [ label=<<table border='0'><tr><td>cadd</td></tr></table>>, color="green" ];
    node_158 [ label=<<table border='0'><tr><td>motif3</td></tr></table>>, color="black" ];
    node_157 -> node_158 [ arrowhead=none ];
    node_159 [ label=<<table border='0'><tr><td>tail2</td></tr></table>>, color="black" ];
    node_157 -> node_159 [ arrowhead=none ];
    node_160 [ label=h, fontcolor="purple", shape=none ];
    node_155 -> node_160 [ arrowhead=none, color="purple", weight=99 ];
    { rank=same node_155 node_156 node_157 }
}
node_160 -> node_161 [ style=invis ];
subgraph cluster_11 {
    node_161 [ label=<<table border='0'><tr><td>motif3</td></tr></table>>, color="black", shape="box" ];
    node_161 -> node_162 [ style=invis, weight=99 ];
    node_162 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_162 -> node_163 [ style=invis ];
    node_163 [ label=<<table border='0'><tr><td>dlr</td></tr></table>>, color="green" ];
    node_164 [ label=<<table border='0'><tr><td>LOC</td></tr></table>>, color="blue" ];
    node_163 -> node_164 [ arrowhead=none ];
    node_165 [ label=<<table border='0'><tr><td>stem3</td></tr></table>>, color="black" ];
    node_163 -> node_165 [ arrowhead=none ];
    node_166 [ label=<<table border='0'><tr><td>LOC</td></tr></table>>, color="blue" ];
    node_163 -> node_166 [ arrowhead=none ];
    node_167 [ label=h, fontcolor="purple", shape=none ];
    node_161 -> node_167 [ arrowhead=none, color="purple", weight=99 ];
    { rank=same node_161 node_162 node_163 }
}
node_167 -> node_168 [ style=invis ];
subgraph cluster_12 {
    node_168 [ label=<<table border='0'><tr><td>stem3</td></tr></table>>, color="black", shape="box", style="dotted" ];
    node_168 -> node_169 [ style=invis, weight=99 ];
    node_169 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_169 -> node_170 [ style=invis ];
    node_170 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_171 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_170 -> node_171 [ arrowhead=none, color="magenta" ];
    node_172 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_170 -> node_172 [ arrowhead=none ];
    node_173 [ label=<<table border='0'><tr><td>maxstem3</td></tr></table>>, color="black" ];
    node_170 -> node_173 [ arrowhead=none ];
    node_174 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_170 -> node_174 [ arrowhead=none ];
    node_175 [ label=h, fontcolor="purple", shape=none ];
    node_168 -> node_175 [ arrowhead=none, color="purple", weight=99 ];
    { rank=same node_168 node_169 node_170 }
}
node_175 -> node_176 [ style=invis ];
subgraph cluster_13 {
    node_176 [ label=<<table border='0'><tr><td>maxstem3</td></tr></table>>, color="black", shape="box", style="dotted" ];
    node_176 -> node_177 [ style=invis, weight=99 ];
    node_177 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_177 -> node_178 [ style=invis ];
    node_178 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_179 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_178 -> node_179 [ arrowhead=none, color="magenta" ];
    node_180 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_178 -> node_180 [ arrowhead=none ];
    node_181 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_182 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_181 -> node_182 [ ];
    node_183 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_184 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_183 -> node_184 [ arrowhead=none, color="magenta" ];
    node_185 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_183 -> node_185 [ arrowhead=none ];
    node_186 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_187 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_186 -> node_187 [ ];
    node_188 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_189 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_188 -> node_189 [ arrowhead=none, color="magenta" ];
    node_190 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_188 -> node_190 [ arrowhead=none ];
    node_191 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_192 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_191 -> node_192 [ ];
    node_193 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_194 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_193 -> node_194 [ arrowhead=none, color="magenta" ];
    node_195 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_193 -> node_195 [ arrowhead=none ];
    node_196 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_197 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_196 -> node_197 [ ];
    node_198 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_199 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_198 -> node_199 [ arrowhead=none, color="magenta" ];
    node_200 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_198 -> node_200 [ arrowhead=none ];
    node_201 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_202 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_201 -> node_202 [ ];
    node_203 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_204 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_203 -> node_204 [ arrowhead=none, color="magenta" ];
    node_205 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_203 -> node_205 [ arrowhead=none ];
    node_206 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_207 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_206 -> node_207 [ ];
    node_208 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_209 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_208 -> node_209 [ arrowhead=none, color="magenta" ];
    node_210 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_208 -> node_210 [ arrowhead=none ];
    node_211 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_212 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_211 -> node_212 [ ];
    node_213 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_214 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_213 -> node_214 [ arrowhead=none, color="magenta" ];
    node_215 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_213 -> node_215 [ arrowhead=none ];
    node_216 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_217 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_216 -> node_217 [ ];
    node_218 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_219 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_218 -> node_219 [ arrowhead=none, color="magenta" ];
    node_220 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_218 -> node_220 [ arrowhead=none ];
    node_221 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_222 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_221 -> node_222 [ ];
    node_223 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_224 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_223 -> node_224 [ arrowhead=none, color="magenta" ];
    node_225 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_223 -> node_225 [ arrowhead=none ];
    node_226 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_227 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_226 -> node_227 [ ];
    node_228 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_229 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_228 -> node_229 [ arrowhead=none, color="magenta" ];
    node_230 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_228 -> node_230 [ arrowhead=none ];
    node_231 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_232 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_231 -> node_232 [ ];
    node_233 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_234 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_233 -> node_234 [ arrowhead=none, color="magenta" ];
    node_235 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_233 -> node_235 [ arrowhead=none ];
    node_236 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_237 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_236 -> node_237 [ ];
    node_238 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_239 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_238 -> node_239 [ arrowhead=none, color="magenta" ];
    node_240 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_238 -> node_240 [ arrowhead=none ];
    node_241 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_242 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_241 -> node_242 [ ];
    node_243 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_244 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_243 -> node_244 [ arrowhead=none, color="magenta" ];
    node_245 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_243 -> node_245 [ arrowhead=none ];
    node_246 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_247 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_246 -> node_247 [ ];
    node_248 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_249 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_248 -> node_249 [ arrowhead=none, color="magenta" ];
    node_250 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_248 -> node_250 [ arrowhead=none ];
    node_251 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_252 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_251 -> node_252 [ ];
    node_253 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_254 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_253 -> node_254 [ arrowhead=none, color="magenta" ];
    node_255 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_253 -> node_255 [ arrowhead=none ];
    node_256 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_257 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_256 -> node_257 [ ];
    node_258 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_259 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_258 -> node_259 [ arrowhead=none, color="magenta" ];
    node_260 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_258 -> node_260 [ arrowhead=none ];
    node_261 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_262 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_261 -> node_262 [ ];
    node_263 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_264 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_263 -> node_264 [ arrowhead=none, color="magenta" ];
    node_265 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_263 -> node_265 [ arrowhead=none ];
    node_266 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_267 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_266 -> node_267 [ ];
    node_268 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_269 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_268 -> node_269 [ arrowhead=none, color="magenta" ];
    node_270 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_268 -> node_270 [ arrowhead=none ];
    node_271 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_272 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_271 -> node_272 [ ];
    node_273 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_274 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_273 -> node_274 [ arrowhead=none, color="magenta" ];
    node_275 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_273 -> node_275 [ arrowhead=none ];
    node_276 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_277 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_276 -> node_277 [ ];
    node_278 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_279 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_278 -> node_279 [ arrowhead=none, color="magenta" ];
    node_280 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_278 -> node_280 [ arrowhead=none ];
    node_281 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_282 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_281 -> node_282 [ ];
    node_283 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_284 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_283 -> node_284 [ arrowhead=none, color="magenta" ];
    node_285 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_283 -> node_285 [ arrowhead=none ];
    node_286 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_287 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_286 -> node_287 [ ];
    node_288 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_289 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_288 -> node_289 [ arrowhead=none, color="magenta" ];
    node_290 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_288 -> node_290 [ arrowhead=none ];
    node_291 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_292 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_291 -> node_292 [ ];
    node_293 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_294 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_293 -> node_294 [ arrowhead=none, color="magenta" ];
    node_295 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_293 -> node_295 [ arrowhead=none ];
    node_296 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
    node_293 -> node_296 [ arrowhead=none ];
    node_297 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_293 -> node_297 [ arrowhead=none ];
    node_291 -> node_293 [ ];
    node_288 -> node_291 [ arrowhead=none ];
    node_298 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_288 -> node_298 [ arrowhead=none ];
    node_286 -> node_288 [ ];
    node_283 -> node_286 [ arrowhead=none ];
    node_299 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_283 -> node_299 [ arrowhead=none ];
    node_281 -> node_283 [ ];
    node_278 -> node_281 [ arrowhead=none ];
    node_300 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_278 -> node_300 [ arrowhead=none ];
    node_276 -> node_278 [ ];
    node_273 -> node_276 [ arrowhead=none ];
    node_301 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_273 -> node_301 [ arrowhead=none ];
    node_271 -> node_273 [ ];
    node_268 -> node_271 [ arrowhead=none ];
    node_302 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_268 -> node_302 [ arrowhead=none ];
    node_266 -> node_268 [ ];
    node_263 -> node_266 [ arrowhead=none ];
    node_303 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_263 -> node_303 [ arrowhead=none ];
    node_261 -> node_263 [ ];
    node_258 -> node_261 [ arrowhead=none ];
    node_304 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_258 -> node_304 [ arrowhead=none ];
    node_256 -> node_258 [ ];
    node_253 -> node_256 [ arrowhead=none ];
    node_305 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_253 -> node_305 [ arrowhead=none ];
    node_251 -> node_253 [ ];
    node_248 -> node_251 [ arrowhead=none ];
    node_306 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_248 -> node_306 [ arrowhead=none ];
    node_246 -> node_248 [ ];
    node_243 -> node_246 [ arrowhead=none ];
    node_307 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_243 -> node_307 [ arrowhead=none ];
    node_241 -> node_243 [ ];
    node_238 -> node_241 [ arrowhead=none ];
    node_308 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_238 -> node_308 [ arrowhead=none ];
    node_236 -> node_238 [ ];
    node_233 -> node_236 [ arrowhead=none ];
    node_309 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_233 -> node_309 [ arrowhead=none ];
    node_231 -> node_233 [ ];
    node_228 -> node_231 [ arrowhead=none ];
    node_310 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_228 -> node_310 [ arrowhead=none ];
    node_226 -> node_228 [ ];
    node_223 -> node_226 [ arrowhead=none ];
    node_311 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_223 -> node_311 [ arrowhead=none ];
    node_221 -> node_223 [ ];
    node_218 -> node_221 [ arrowhead=none ];
    node_312 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_218 -> node_312 [ arrowhead=none ];
    node_216 -> node_218 [ ];
    node_213 -> node_216 [ arrowhead=none ];
    node_313 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_213 -> node_313 [ arrowhead=none ];
    node_211 -> node_213 [ ];
    node_208 -> node_211 [ arrowhead=none ];
    node_314 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_208 -> node_314 [ arrowhead=none ];
    node_206 -> node_208 [ ];
    node_203 -> node_206 [ arrowhead=none ];
    node_315 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_203 -> node_315 [ arrowhead=none ];
    node_201 -> node_203 [ ];
    node_198 -> node_201 [ arrowhead=none ];
    node_316 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_198 -> node_316 [ arrowhead=none ];
    node_196 -> node_198 [ ];
    node_193 -> node_196 [ arrowhead=none ];
    node_317 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_193 -> node_317 [ arrowhead=none ];
    node_191 -> node_193 [ ];
    node_188 -> node_191 [ arrowhead=none ];
    node_318 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_188 -> node_318 [ arrowhead=none ];
    node_186 -> node_188 [ ];
    node_183 -> node_186 [ arrowhead=none ];
    node_319 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_183 -> node_319 [ arrowhead=none ];
    node_181 -> node_183 [ ];
    node_178 -> node_181 [ arrowhead=none ];
    node_320 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_178 -> node_320 [ arrowhead=none ];
    node_321 [ label=h, fontcolor="purple", shape=none ];
    node_176 -> node_321 [ arrowhead=none, color="purple", weight=99 ];
    node_321 -> node_322 [ style=invis, weight=99 ];
    node_322 [ style=invis ];
    node_322 -> node_323 [ style=invis, weight=99 ];
    node_323 [ style=invis ];
    node_323 -> node_324 [ style=invis, weight=99 ];
    node_324 [ style=invis ];
    node_324 -> node_325 [ style=invis, weight=99 ];
    node_325 [ style=invis ];
    node_325 -> node_326 [ style=invis, weight=99 ];
    node_326 [ style=invis ];
    node_326 -> node_327 [ style=invis, weight=99 ];
    node_327 [ style=invis ];
    node_327 -> node_328 [ style=invis, weight=99 ];
    node_328 [ style=invis ];
    node_328 -> node_329 [ style=invis, weight=99 ];
    node_329 [ style=invis ];
    node_329 -> node_330 [ style=invis, weight=99 ];
    node_330 [ style=invis ];
    node_330 -> node_331 [ style=invis, weight=99 ];
    node_331 [ style=invis ];
    node_331 -> node_332 [ style=invis, weight=99 ];
    node_332 [ style=invis ];
    node_332 -> node_333 [ style=invis, weight=99 ];
    node_333 [ style=invis ];
    node_333 -> node_334 [ style=invis, weight=99 ];
    node_334 [ style=invis ];
    node_334 -> node_335 [ style=invis, weight=99 ];
    node_335 [ style=invis ];
    node_335 -> node_336 [ style=invis, weight=99 ];
    node_336 [ style=invis ];
    node_336 -> node_337 [ style=invis, weight=99 ];
    node_337 [ style=invis ];
    node_337 -> node_338 [ style=invis, weight=99 ];
    node_338 [ style=invis ];
    node_338 -> node_339 [ style=invis, weight=99 ];
    node_339 [ style=invis ];
    node_339 -> node_340 [ style=invis, weight=99 ];
    node_340 [ style=invis ];
    node_340 -> node_341 [ style=invis, weight=99 ];
    node_341 [ style=invis ];
    node_341 -> node_342 [ style=invis, weight=99 ];
    node_342 [ style=invis ];
    node_342 -> node_343 [ style=invis, weight=99 ];
    node_343 [ style=invis ];
    node_343 -> node_344 [ style=invis, weight=99 ];
    node_344 [ style=invis ];
    node_344 -> node_345 [ style=invis, weight=99 ];
    node_345 [ style=invis ];
    node_345 -> node_346 [ style=invis, weight=99 ];
    node_346 [ style=invis ];
    node_346 -> node_347 [ style=invis, weight=99 ];
    node_347 [ style=invis ];
    node_347 -> node_348 [ style=invis, weight=99 ];
    node_348 [ style=invis ];
    node_348 -> node_349 [ style=invis, weight=99 ];
    node_349 [ style=invis ];
    node_349 -> node_350 [ style=invis, weight=99 ];
    node_350 [ style=invis ];
    node_350 -> node_351 [ style=invis, weight=99 ];
    node_351 [ style=invis ];
    node_351 -> node_352 [ style=invis, weight=99 ];
    node_352 [ style=invis ];
    node_352 -> node_353 [ style=invis, weight=99 ];
    node_353 [ style=invis ];
    node_353 -> node_354 [ style=invis, weight=99 ];
    node_354 [ style=invis ];
    node_354 -> node_355 [ style=invis, weight=99 ];
    node_355 [ style=invis ];
    node_355 -> node_356 [ style=invis, weight=99 ];
    node_356 [ style=invis ];
    node_356 -> node_357 [ style=invis, weight=99 ];
    node_357 [ style=invis ];
    node_357 -> node_358 [ style=invis, weight=99 ];
    node_358 [ style=invis ];
    node_358 -> node_359 [ style=invis, weight=99 ];
    node_359 [ style=invis ];
    node_359 -> node_360 [ style=invis, weight=99 ];
    node_360 [ style=invis ];
    node_360 -> node_361 [ style=invis, weight=99 ];
    node_361 [ style=invis ];
    node_361 -> node_362 [ style=invis, weight=99 ];
    node_362 [ style=invis ];
    node_362 -> node_363 [ style=invis, weight=99 ];
    node_363 [ style=invis ];
    node_363 -> node_364 [ style=invis, weight=99 ];
    node_364 [ style=invis ];
    node_364 -> node_365 [ style=invis, weight=99 ];
    node_365 [ style=invis ];
    node_365 -> node_366 [ style=invis, weight=99 ];
    node_366 [ style=invis ];
    node_366 -> node_367 [ style=invis, weight=99 ];
    node_367 [ style=invis ];
    { rank=same node_176 node_177 node_178 }
}
node_367 -> node_368 [ style=invis ];
subgraph cluster_14 {
    node_368 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black", shape="box", style="dotted" ];
    node_368 -> node_369 [ style=invis, weight=99 ];
    node_369 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_369 -> node_370 [ style=invis ];
    node_370 [ label=<<table border='0'><tr><td>hairpin4</td></tr></table>>, color="black" ];
    node_371 [ label=h, fontcolor="purple", shape=none ];
    node_368 -> node_371 [ arrowhead=none, color="purple", weight=99 ];
    { rank=same node_368 node_369 node_370 }
}
node_371 -> node_372 [ style=invis ];
subgraph cluster_15 {
    node_372 [ label=<<table border='0'><tr><td>hairpin4</td></tr></table>>, color="black", shape="box", style="dotted" ];
    node_372 -> node_373 [ style=invis, weight=99 ];
    node_373 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_373 -> node_374 [ style=invis ];
    node_374 [ label=<<table border='0'><tr><td>hl</td></tr></table>>, color="green" ];
    node_375 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_374 -> node_375 [ arrowhead=none, color="magenta" ];
    node_376 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_374 -> node_376 [ arrowhead=none ];
    node_377 [ label=<<table border='0'><tr><td>REGION</td></tr></table>>, color="blue" ];
    node_378 [ label="minsize(3)" , fontcolor="magenta" , shape=none ];
    node_377 -> node_378 [ arrowhead=none, color="magenta" ];
    node_374 -> node_377 [ arrowhead=none ];
    node_379 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_374 -> node_379 [ arrowhead=none ];
    node_380 [ label=h, fontcolor="purple", shape=none ];
    node_372 -> node_380 [ arrowhead=none, color="purple", weight=99 ];
    node_380 -> node_381 [ style=invis, weight=99 ];
    node_381 [ style=invis ];
    { rank=same node_372 node_373 node_374 }
}
node_381 -> node_382 [ style=invis ];
subgraph cluster_16 {
    node_382 [ label=<<table border='0'><tr><td>tail2</td></tr></table>>, color="black", shape="box" ];
    node_382 -> node_383 [ style=invis, weight=99 ];
    node_383 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_383 -> node_384 [ style=invis ];
    node_384 [ label=<<table border='0'><tr><td>cadd</td></tr></table>>, color="green" ];
    node_385 [ label=<<table border='0'><tr><td>motif5</td></tr></table>>, color="black" ];
    node_384 -> node_385 [ arrowhead=none ];
    node_386 [ label=<<table border='0'><tr><td>tail3</td></tr></table>>, color="black" ];
    node_384 -> node_386 [ arrowhead=none ];
    node_387 [ label=h, fontcolor="purple", shape=none ];
    node_382 -> node_387 [ arrowhead=none, color="purple", weight=99 ];
    { rank=same node_382 node_383 node_384 }
}
node_387 -> node_388 [ style=invis ];
subgraph cluster_17 {
    node_388 [ label=<<table border='0'><tr><td>motif5</td></tr></table>>, color="black", shape="box" ];
    node_388 -> node_389 [ style=invis, weight=99 ];
    node_389 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_389 -> node_390 [ style=invis ];
    node_390 [ label=<<table border='0'><tr><td>ss</td></tr></table>>, color="green" ];
    node_391 [ label=<<table border='0'><tr><td>UREGION</td></tr></table>>, color="blue" ];
    node_390 -> node_391 [ arrowhead=none ];
    node_392 [ label=h, fontcolor="purple", shape=none ];
    node_388 -> node_392 [ arrowhead=none, color="purple", weight=99 ];
    { rank=same node_388 node_389 node_390 }
}
node_392 -> node_393 [ style=invis ];
subgraph cluster_18 {
    node_393 [ label=<<table border='0'><tr><td>tail3</td></tr></table>>, color="black", shape="box" ];
    node_393 -> node_394 [ style=invis, weight=99 ];
    node_394 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_394 -> node_395 [ style=invis ];
    node_395 [ label=<<table border='0'><tr><td>motif6</td></tr></table>>, color="black" ];
    { rank=same node_393 node_394 node_395 }
}
node_393 -> node_396 [ style=invis ];
subgraph cluster_19 {
    node_396 [ label=<<table border='0'><tr><td>motif6</td></tr></table>>, color="black", shape="box", style="dotted" ];
    node_396 -> node_397 [ style=invis, weight=99 ];
    node_397 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_397 -> node_398 [ style=invis ];
    node_398 [ label=<<table border='0'><tr><td>dlr</td></tr></table>>, color="green" ];
    node_399 [ label=<<table border='0'><tr><td>LOC</td></tr></table>>, color="blue" ];
    node_398 -> node_399 [ arrowhead=none ];
    node_400 [ label=<<table border='0'><tr><td>stem6</td></tr></table>>, color="black" ];
    node_398 -> node_400 [ arrowhead=none ];
    node_401 [ label=<<table border='0'><tr><td>LOC</td></tr></table>>, color="blue" ];
    node_398 -> node_401 [ arrowhead=none ];
    node_402 [ label=h, fontcolor="purple", shape=none ];
    node_396 -> node_402 [ arrowhead=none, color="purple", weight=99 ];
    { rank=same node_396 node_397 node_398 }
}
node_402 -> node_403 [ style=invis ];
subgraph cluster_20 {
    node_403 [ label=<<table border='0'><tr><td>stem6</td></tr></table>>, color="black", shape="box", style="dotted" ];
    node_403 -> node_404 [ style=invis, weight=99 ];
    node_404 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_404 -> node_405 [ style=invis ];
    node_405 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_406 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_405 -> node_406 [ arrowhead=none, color="magenta" ];
    node_407 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_405 -> node_407 [ arrowhead=none ];
    node_408 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_409 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_408 -> node_409 [ arrowhead=none, color="magenta" ];
    node_410 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_408 -> node_410 [ arrowhead=none ];
    node_411 [ label=<<table border='0'><tr><td>maxstem6</td></tr></table>>, color="black" ];
    node_408 -> node_411 [ arrowhead=none ];
    node_412 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_408 -> node_412 [ arrowhead=none ];
    node_405 -> node_408 [ arrowhead=none ];
    node_413 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_405 -> node_413 [ arrowhead=none ];
    node_414 [ label=h, fontcolor="purple", shape=none ];
    node_403 -> node_414 [ arrowhead=none, color="purple", weight=99 ];
    node_414 -> node_415 [ style=invis, weight=99 ];
    node_415 [ style=invis ];
    { rank=same node_403 node_404 node_405 }
}
node_415 -> node_416 [ style=invis ];
subgraph cluster_21 {
    node_416 [ label=<<table border='0'><tr><td>maxstem6</td></tr></table>>, color="black", shape="box", style="dotted" ];
    node_416 -> node_417 [ style=invis, weight=99 ];
    node_417 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_417 -> node_418 [ style=invis ];
    node_418 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_419 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_418 -> node_419 [ arrowhead=none, color="magenta" ];
    node_420 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_418 -> node_420 [ arrowhead=none ];
    node_421 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_422 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_421 -> node_422 [ ];
    node_423 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_424 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_423 -> node_424 [ arrowhead=none, color="magenta" ];
    node_425 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_423 -> node_425 [ arrowhead=none ];
    node_426 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_427 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_426 -> node_427 [ ];
    node_428 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_429 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_428 -> node_429 [ arrowhead=none, color="magenta" ];
    node_430 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_428 -> node_430 [ arrowhead=none ];
    node_431 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_432 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_431 -> node_432 [ ];
    node_433 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_434 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_433 -> node_434 [ arrowhead=none, color="magenta" ];
    node_435 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_433 -> node_435 [ arrowhead=none ];
    node_436 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_437 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_436 -> node_437 [ ];
    node_438 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_439 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_438 -> node_439 [ arrowhead=none, color="magenta" ];
    node_440 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_438 -> node_440 [ arrowhead=none ];
    node_441 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_442 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_441 -> node_442 [ ];
    node_443 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_444 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_443 -> node_444 [ arrowhead=none, color="magenta" ];
    node_445 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_443 -> node_445 [ arrowhead=none ];
    node_446 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_447 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_446 -> node_447 [ ];
    node_448 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_449 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_448 -> node_449 [ arrowhead=none, color="magenta" ];
    node_450 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_448 -> node_450 [ arrowhead=none ];
    node_451 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_452 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_451 -> node_452 [ ];
    node_453 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_454 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_453 -> node_454 [ arrowhead=none, color="magenta" ];
    node_455 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_453 -> node_455 [ arrowhead=none ];
    node_456 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_457 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_456 -> node_457 [ ];
    node_458 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_459 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_458 -> node_459 [ arrowhead=none, color="magenta" ];
    node_460 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_458 -> node_460 [ arrowhead=none ];
    node_461 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_462 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_461 -> node_462 [ ];
    node_463 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_464 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_463 -> node_464 [ arrowhead=none, color="magenta" ];
    node_465 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_463 -> node_465 [ arrowhead=none ];
    node_466 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_467 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_466 -> node_467 [ ];
    node_468 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_469 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_468 -> node_469 [ arrowhead=none, color="magenta" ];
    node_470 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_468 -> node_470 [ arrowhead=none ];
    node_471 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_472 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_471 -> node_472 [ ];
    node_473 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_474 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_473 -> node_474 [ arrowhead=none, color="magenta" ];
    node_475 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_473 -> node_475 [ arrowhead=none ];
    node_476 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_477 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_476 -> node_477 [ ];
    node_478 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_479 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_478 -> node_479 [ arrowhead=none, color="magenta" ];
    node_480 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_478 -> node_480 [ arrowhead=none ];
    node_481 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_482 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_481 -> node_482 [ ];
    node_483 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_484 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_483 -> node_484 [ arrowhead=none, color="magenta" ];
    node_485 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_483 -> node_485 [ arrowhead=none ];
    node_486 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_487 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_486 -> node_487 [ ];
    node_488 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_489 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_488 -> node_489 [ arrowhead=none, color="magenta" ];
    node_490 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_488 -> node_490 [ arrowhead=none ];
    node_491 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_492 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_491 -> node_492 [ ];
    node_493 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_494 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_493 -> node_494 [ arrowhead=none, color="magenta" ];
    node_495 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_493 -> node_495 [ arrowhead=none ];
    node_496 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_497 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_496 -> node_497 [ ];
    node_498 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_499 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_498 -> node_499 [ arrowhead=none, color="magenta" ];
    node_500 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_498 -> node_500 [ arrowhead=none ];
    node_501 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_502 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_501 -> node_502 [ ];
    node_503 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_504 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_503 -> node_504 [ arrowhead=none, color="magenta" ];
    node_505 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_503 -> node_505 [ arrowhead=none ];
    node_506 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_507 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_506 -> node_507 [ ];
    node_508 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_509 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_508 -> node_509 [ arrowhead=none, color="magenta" ];
    node_510 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_508 -> node_510 [ arrowhead=none ];
    node_511 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_512 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_511 -> node_512 [ ];
    node_513 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_514 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_513 -> node_514 [ arrowhead=none, color="magenta" ];
    node_515 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_513 -> node_515 [ arrowhead=none ];
    node_516 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_517 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_516 -> node_517 [ ];
    node_518 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_519 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_518 -> node_519 [ arrowhead=none, color="magenta" ];
    node_520 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_518 -> node_520 [ arrowhead=none ];
    node_521 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_522 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_521 -> node_522 [ ];
    node_523 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_524 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_523 -> node_524 [ arrowhead=none, color="magenta" ];
    node_525 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_523 -> node_525 [ arrowhead=none ];
    node_526 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_527 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_526 -> node_527 [ ];
    node_528 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_529 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_528 -> node_529 [ arrowhead=none, color="magenta" ];
    node_530 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_528 -> node_530 [ arrowhead=none ];
    node_531 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_532 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_531 -> node_532 [ ];
    node_533 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_534 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_533 -> node_534 [ arrowhead=none, color="magenta" ];
    node_535 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_533 -> node_535 [ arrowhead=none ];
    node_536 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_537 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_536 -> node_537 [ ];
    node_538 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_539 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_538 -> node_539 [ arrowhead=none, color="magenta" ];
    node_540 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_538 -> node_540 [ arrowhead=none ];
    node_541 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_542 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_541 -> node_542 [ ];
    node_543 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_544 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_543 -> node_544 [ arrowhead=none, color="magenta" ];
    node_545 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_543 -> node_545 [ arrowhead=none ];
    node_546 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_547 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_546 -> node_547 [ ];
    node_548 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_549 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_548 -> node_549 [ arrowhead=none, color="magenta" ];
    node_550 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_548 -> node_550 [ arrowhead=none ];
    node_551 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
    node_552 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_551 -> node_552 [ ];
    node_553 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
    node_554 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_553 -> node_554 [ arrowhead=none, color="magenta" ];
    node_555 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_553 -> node_555 [ arrowhead=none ];
    node_556 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
    node_553 -> node_556 [ arrowhead=none ];
    node_557 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_553 -> node_557 [ arrowhead=none ];
    node_551 -> node_553 [ ];
    node_548 -> node_551 [ arrowhead=none ];
    node_558 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_548 -> node_558 [ arrowhead=none ];
    node_546 -> node_548 [ ];
    node_543 -> node_546 [ arrowhead=none ];
    node_559 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_543 -> node_559 [ arrowhead=none ];
    node_541 -> node_543 [ ];
    node_538 -> node_541 [ arrowhead=none ];
    node_560 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_538 -> node_560 [ arrowhead=none ];
    node_536 -> node_538 [ ];
    node_533 -> node_536 [ arrowhead=none ];
    node_561 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_533 -> node_561 [ arrowhead=none ];
    node_531 -> node_533 [ ];
    node_528 -> node_531 [ arrowhead=none ];
    node_562 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_528 -> node_562 [ arrowhead=none ];
    node_526 -> node_528 [ ];
    node_523 -> node_526 [ arrowhead=none ];
    node_563 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_523 -> node_563 [ arrowhead=none ];
    node_521 -> node_523 [ ];
    node_518 -> node_521 [ arrowhead=none ];
    node_564 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_518 -> node_564 [ arrowhead=none ];
    node_516 -> node_518 [ ];
    node_513 -> node_516 [ arrowhead=none ];
    node_565 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_513 -> node_565 [ arrowhead=none ];
    node_511 -> node_513 [ ];
    node_508 -> node_511 [ arrowhead=none ];
    node_566 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_508 -> node_566 [ arrowhead=none ];
    node_506 -> node_508 [ ];
    node_503 -> node_506 [ arrowhead=none ];
    node_567 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_503 -> node_567 [ arrowhead=none ];
    node_501 -> node_503 [ ];
    node_498 -> node_501 [ arrowhead=none ];
    node_568 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_498 -> node_568 [ arrowhead=none ];
    node_496 -> node_498 [ ];
    node_493 -> node_496 [ arrowhead=none ];
    node_569 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_493 -> node_569 [ arrowhead=none ];
    node_491 -> node_493 [ ];
    node_488 -> node_491 [ arrowhead=none ];
    node_570 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_488 -> node_570 [ arrowhead=none ];
    node_486 -> node_488 [ ];
    node_483 -> node_486 [ arrowhead=none ];
    node_571 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_483 -> node_571 [ arrowhead=none ];
    node_481 -> node_483 [ ];
    node_478 -> node_481 [ arrowhead=none ];
    node_572 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_478 -> node_572 [ arrowhead=none ];
    node_476 -> node_478 [ ];
    node_473 -> node_476 [ arrowhead=none ];
    node_573 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_473 -> node_573 [ arrowhead=none ];
    node_471 -> node_473 [ ];
    node_468 -> node_471 [ arrowhead=none ];
    node_574 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_468 -> node_574 [ arrowhead=none ];
    node_466 -> node_468 [ ];
    node_463 -> node_466 [ arrowhead=none ];
    node_575 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_463 -> node_575 [ arrowhead=none ];
    node_461 -> node_463 [ ];
    node_458 -> node_461 [ arrowhead=none ];
    node_576 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_458 -> node_576 [ arrowhead=none ];
    node_456 -> node_458 [ ];
    node_453 -> node_456 [ arrowhead=none ];
    node_577 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_453 -> node_577 [ arrowhead=none ];
    node_451 -> node_453 [ ];
    node_448 -> node_451 [ arrowhead=none ];
    node_578 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_448 -> node_578 [ arrowhead=none ];
    node_446 -> node_448 [ ];
    node_443 -> node_446 [ arrowhead=none ];
    node_579 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_443 -> node_579 [ arrowhead=none ];
    node_441 -> node_443 [ ];
    node_438 -> node_441 [ arrowhead=none ];
    node_580 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_438 -> node_580 [ arrowhead=none ];
    node_436 -> node_438 [ ];
    node_433 -> node_436 [ arrowhead=none ];
    node_581 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_433 -> node_581 [ arrowhead=none ];
    node_431 -> node_433 [ ];
    node_428 -> node_431 [ arrowhead=none ];
    node_582 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_428 -> node_582 [ arrowhead=none ];
    node_426 -> node_428 [ ];
    node_423 -> node_426 [ arrowhead=none ];
    node_583 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_423 -> node_583 [ arrowhead=none ];
    node_421 -> node_423 [ ];
    node_418 -> node_421 [ arrowhead=none ];
    node_584 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_418 -> node_584 [ arrowhead=none ];
    node_585 [ label=h, fontcolor="purple", shape=none ];
    node_416 -> node_585 [ arrowhead=none, color="purple", weight=99 ];
    node_585 -> node_586 [ style=invis, weight=99 ];
    node_586 [ style=invis ];
    node_586 -> node_587 [ style=invis, weight=99 ];
    node_587 [ style=invis ];
    node_587 -> node_588 [ style=invis, weight=99 ];
    node_588 [ style=invis ];
    node_588 -> node_589 [ style=invis, weight=99 ];
    node_589 [ style=invis ];
    node_589 -> node_590 [ style=invis, weight=99 ];
    node_590 [ style=invis ];
    node_590 -> node_591 [ style=invis, weight=99 ];
    node_591 [ style=invis ];
    node_591 -> node_592 [ style=invis, weight=99 ];
    node_592 [ style=invis ];
    node_592 -> node_593 [ style=invis, weight=99 ];
    node_593 [ style=invis ];
    node_593 -> node_594 [ style=invis, weight=99 ];
    node_594 [ style=invis ];
    node_594 -> node_595 [ style=invis, weight=99 ];
    node_595 [ style=invis ];
    node_595 -> node_596 [ style=invis, weight=99 ];
    node_596 [ style=invis ];
    node_596 -> node_597 [ style=invis, weight=99 ];
    node_597 [ style=invis ];
    node_597 -> node_598 [ style=invis, weight=99 ];
    node_598 [ style=invis ];
    node_598 -> node_599 [ style=invis, weight=99 ];
    node_599 [ style=invis ];
    node_599 -> node_600 [ style=invis, weight=99 ];
    node_600 [ style=invis ];
    node_600 -> node_601 [ style=invis, weight=99 ];
    node_601 [ style=invis ];
    node_601 -> node_602 [ style=invis, weight=99 ];
    node_602 [ style=invis ];
    node_602 -> node_603 [ style=invis, weight=99 ];
    node_603 [ style=invis ];
    node_603 -> node_604 [ style=invis, weight=99 ];
    node_604 [ style=invis ];
    node_604 -> node_605 [ style=invis, weight=99 ];
    node_605 [ style=invis ];
    node_605 -> node_606 [ style=invis, weight=99 ];
    node_606 [ style=invis ];
    node_606 -> node_607 [ style=invis, weight=99 ];
    node_607 [ style=invis ];
    node_607 -> node_608 [ style=invis, weight=99 ];
    node_608 [ style=invis ];
    node_608 -> node_609 [ style=invis, weight=99 ];
    node_609 [ style=invis ];
    node_609 -> node_610 [ style=invis, weight=99 ];
    node_610 [ style=invis ];
    node_610 -> node_611 [ style=invis, weight=99 ];
    node_611 [ style=invis ];
    node_611 -> node_612 [ style=invis, weight=99 ];
    node_612 [ style=invis ];
    node_612 -> node_613 [ style=invis, weight=99 ];
    node_613 [ style=invis ];
    node_613 -> node_614 [ style=invis, weight=99 ];
    node_614 [ style=invis ];
    node_614 -> node_615 [ style=invis, weight=99 ];
    node_615 [ style=invis ];
    node_615 -> node_616 [ style=invis, weight=99 ];
    node_616 [ style=invis ];
    node_616 -> node_617 [ style=invis, weight=99 ];
    node_617 [ style=invis ];
    node_617 -> node_618 [ style=invis, weight=99 ];
    node_618 [ style=invis ];
    node_618 -> node_619 [ style=invis, weight=99 ];
    node_619 [ style=invis ];
    node_619 -> node_620 [ style=invis, weight=99 ];
    node_620 [ style=invis ];
    node_620 -> node_621 [ style=invis, weight=99 ];
    node_621 [ style=invis ];
    node_621 -> node_622 [ style=invis, weight=99 ];
    node_622 [ style=invis ];
    node_622 -> node_623 [ style=invis, weight=99 ];
    node_623 [ style=invis ];
    node_623 -> node_624 [ style=invis, weight=99 ];
    node_624 [ style=invis ];
    node_624 -> node_625 [ style=invis, weight=99 ];
    node_625 [ style=invis ];
    node_625 -> node_626 [ style=invis, weight=99 ];
    node_626 [ style=invis ];
    node_626 -> node_627 [ style=invis, weight=99 ];
    node_627 [ style=invis ];
    node_627 -> node_628 [ style=invis, weight=99 ];
    node_628 [ style=invis ];
    node_628 -> node_629 [ style=invis, weight=99 ];
    node_629 [ style=invis ];
    node_629 -> node_630 [ style=invis, weight=99 ];
    node_630 [ style=invis ];
    node_630 -> node_631 [ style=invis, weight=99 ];
    node_631 [ style=invis ];
    node_631 -> node_632 [ style=invis, weight=99 ];
    node_632 [ style=invis ];
    node_632 -> node_633 [ style=invis, weight=99 ];
    node_633 [ style=invis ];
    node_633 -> node_634 [ style=invis, weight=99 ];
    node_634 [ style=invis ];
    node_634 -> node_635 [ style=invis, weight=99 ];
    node_635 [ style=invis ];
    node_635 -> node_636 [ style=invis, weight=99 ];
    node_636 [ style=invis ];
    node_636 -> node_637 [ style=invis, weight=99 ];
    node_637 [ style=invis ];
    node_637 -> node_638 [ style=invis, weight=99 ];
    node_638 [ style=invis ];
    node_638 -> node_639 [ style=invis, weight=99 ];
    node_639 [ style=invis ];
    { rank=same node_416 node_417 node_418 }
}
node_639 -> node_640 [ style=invis ];
subgraph cluster_22 {
    node_640 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black", shape="box", style="dotted" ];
    node_640 -> node_641 [ style=invis, weight=99 ];
    node_641 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_641 -> node_642 [ style=invis ];
    node_642 [ label=<<table border='0'><tr><td>hairpin7</td></tr></table>>, color="black" ];
    node_643 [ label=h, fontcolor="purple", shape=none ];
    node_640 -> node_643 [ arrowhead=none, color="purple", weight=99 ];
    { rank=same node_640 node_641 node_642 }
}
node_643 -> node_644 [ style=invis ];
subgraph cluster_23 {
    node_644 [ label=<<table border='0'><tr><td>hairpin7</td></tr></table>>, color="black", shape="box", style="dotted" ];
    node_644 -> node_645 [ style=invis, weight=99 ];
    node_645 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_645 -> node_646 [ style=invis ];
    node_646 [ label=<<table border='0'><tr><td>hl</td></tr></table>>, color="green" ];
    node_647 [ label="basepairing" , fontcolor="magenta" , shape=none ];
    node_646 -> node_647 [ arrowhead=none, color="magenta" ];
    node_648 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_646 -> node_648 [ arrowhead=none ];
    node_649 [ label=<<table border='0'><tr><td>REGION</td></tr></table>>, color="blue" ];
    node_650 [ label="minsize(3)" , fontcolor="magenta" , shape=none ];
    node_649 -> node_650 [ arrowhead=none, color="magenta" ];
    node_646 -> node_649 [ arrowhead=none ];
    node_651 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
    node_646 -> node_651 [ arrowhead=none ];
    node_652 [ label=h, fontcolor="purple", shape=none ];
    node_644 -> node_652 [ arrowhead=none, color="purple", weight=99 ];
    node_652 -> node_653 [ style=invis, weight=99 ];
    node_653 [ style=invis ];
    { rank=same node_644 node_645 node_646 }
}
}
