digraph tdm {
compound = True;
newrank=True;
ordering=out;
subgraph cluster_1{
node_1 [ label=<<table border='0'><tr><td>rnastruct</td></tr></table>>, color="black", shape="box", penwidth=3 ];
node_2 [ label=<<table border='0'><tr><td>sadd</td></tr></table>>, color="green" ];
node_3 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_2 -> node_3 [ arrowhead=none ];
node_4 [ label=<<table border='0'><tr><td>rnastruct</td></tr></table>>, color="black" ];
node_2 -> node_4 [ arrowhead=none ];
node_1_2[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_1 -> node_1_2[style= invis, weight=99];
node_1_2 -> node_2[style= invis];
node_5 [ label=<<table border='0'><tr><td>addss</td></tr></table>>, color="green" ];
node_6 [ label=<<table border='0'><tr><td>structstart</td></tr></table>>, color="black" ];
node_5 -> node_6 [ arrowhead=none ];
node_7 [ label=<<table border='0'><tr><td>UREGION</td></tr></table>>, color="blue" ];
node_5 -> node_7 [ arrowhead=none ];
node_2_5[ label=<<table border='0'><tr><td><font point-size='30'>|</font></td></tr></table>>, shape=plaintext];
node_2 -> node_2_5[style= invis];
node_2_5 -> node_5[style= invis];
node_8 [ label=h, fontcolor="purple" , shape=none ];
node_1 -> node_8 [ arrowhead=none, color="purple" , weight=99];
node_9[label = rnastruct, shape="box", style=invis];
node_8 -> node_9[weight = 99, style = invis];
{ rank=same node_1 node_1_2 node_2 node_2_5 node_5 }
}
subgraph cluster_2{
node_10 [ label=<<table border='0'><tr><td>structstart</td></tr></table>>, color="black", shape="box" ];
node_11 [ label=<<table border='0'><tr><td>cadd</td></tr></table>>, color="green" ];
node_12 [ label=<<table border='0'><tr><td>motif0</td></tr></table>>, color="black" ];
node_11 -> node_12 [ arrowhead=none ];
node_13 [ label=<<table border='0'><tr><td>tail0</td></tr></table>>, color="black" ];
node_11 -> node_13 [ arrowhead=none ];
node_10_11[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_10 -> node_10_11[style= invis, weight=99];
node_10_11 -> node_11[style= invis];
node_14 [ label=h, fontcolor="purple" , shape=none ];
node_10 -> node_14 [ arrowhead=none, color="purple" , weight=99];
node_15[label = structstart, shape="box", style=invis];
node_14 -> node_15[weight = 99, style = invis];
{ rank=same node_10 node_10_11 node_11 }
}
node_9 -> node_10 [ style = invis];
subgraph cluster_3{
node_16 [ label=<<table border='0'><tr><td>motif0</td></tr></table>>, color="black", shape="box" ];
node_17 [ label=<<table border='0'><tr><td>dlr</td></tr></table>>, color="green" ];
node_18 [ label=<<table border='0'><tr><td>LOC</td></tr></table>>, color="blue" ];
node_17 -> node_18 [ arrowhead=none ];
node_19 [ label=<<table border='0'><tr><td>stem0</td></tr></table>>, color="black" ];
node_17 -> node_19 [ arrowhead=none ];
node_20 [ label=<<table border='0'><tr><td>LOC</td></tr></table>>, color="blue" ];
node_17 -> node_20 [ arrowhead=none ];
node_16_17[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_16 -> node_16_17[style= invis, weight=99];
node_16_17 -> node_17[style= invis];
node_21 [ label=h, fontcolor="purple" , shape=none ];
node_16 -> node_21 [ arrowhead=none, color="purple" , weight=99];
node_22[label = motif0, shape="box", style=invis];
node_21 -> node_22[weight = 99, style = invis];
{ rank=same node_16 node_16_17 node_17 }
}
node_15 -> node_16 [ style = invis];
subgraph cluster_4{
node_23 [ label=<<table border='0'><tr><td>stem0</td></tr></table>>, color="black", shape="box", style="dotted" ];
node_24 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_25 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_24 -> node_25 [ arrowhead=none, color="magenta" ];
node_26 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_24 -> node_26 [ arrowhead=none ];
node_27 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_28 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_27 -> node_28 [ arrowhead=none, color="magenta" ];
node_29 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_27 -> node_29 [ arrowhead=none ];
node_30 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_31 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_30 -> node_31 [ arrowhead=none, color="magenta" ];
node_32 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_30 -> node_32 [ arrowhead=none ];
node_33 [ label=<<table border='0'><tr><td>maxstem0</td></tr></table>>, color="black" ];
node_30 -> node_33 [ arrowhead=none ];
node_34 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_30 -> node_34 [ arrowhead=none ];
node_27 -> node_30 [ arrowhead=none ];
node_35 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_27 -> node_35 [ arrowhead=none ];
node_24 -> node_27 [ arrowhead=none ];
node_36 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_24 -> node_36 [ arrowhead=none ];
node_23_24[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_23 -> node_23_24[style= invis, weight=99];
node_23_24 -> node_24[style= invis];
node_37 [ label=h, fontcolor="purple" , shape=none ];
node_23 -> node_37 [ arrowhead=none, color="purple" , weight=99];
node_38[label = stem0, shape="box", style=invis];
node_37 -> node_38[weight = 99, style = invis];
node_39[label = stem0, shape="box", style=invis];
node_38 -> node_39[weight = 99, style = invis];
node_40[label = stem0, shape="box", style=invis];
node_39 -> node_40[weight = 99, style = invis];
{ rank=same node_23 node_23_24 node_24 }
}
node_22 -> node_23 [ style = invis];
subgraph cluster_5{
node_41 [ label=<<table border='0'><tr><td>maxstem0</td></tr></table>>, color="black", shape="box", style="dotted" ];
node_42 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_43 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_42 -> node_43 [ arrowhead=none, color="magenta" ];
node_44 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_42 -> node_44 [ arrowhead=none ];
node_45 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_46 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black" ];
node_45 -> node_46 [ ];
node_47 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_48 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_47 -> node_48 [ arrowhead=none, color="magenta" ];
node_49 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_47 -> node_49 [ arrowhead=none ];
node_50 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_51 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black" ];
node_50 -> node_51 [ ];
node_52 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_53 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_52 -> node_53 [ arrowhead=none, color="magenta" ];
node_54 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_52 -> node_54 [ arrowhead=none ];
node_55 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_56 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black" ];
node_55 -> node_56 [ ];
node_57 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_58 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_57 -> node_58 [ arrowhead=none, color="magenta" ];
node_59 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_57 -> node_59 [ arrowhead=none ];
node_60 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_61 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black" ];
node_60 -> node_61 [ ];
node_62 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_63 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_62 -> node_63 [ arrowhead=none, color="magenta" ];
node_64 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_62 -> node_64 [ arrowhead=none ];
node_65 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_66 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black" ];
node_65 -> node_66 [ ];
node_67 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_68 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_67 -> node_68 [ arrowhead=none, color="magenta" ];
node_69 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_67 -> node_69 [ arrowhead=none ];
node_70 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_71 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black" ];
node_70 -> node_71 [ ];
node_72 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_73 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_72 -> node_73 [ arrowhead=none, color="magenta" ];
node_74 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_72 -> node_74 [ arrowhead=none ];
node_75 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_76 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black" ];
node_75 -> node_76 [ ];
node_77 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_78 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_77 -> node_78 [ arrowhead=none, color="magenta" ];
node_79 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_77 -> node_79 [ arrowhead=none ];
node_80 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_81 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black" ];
node_80 -> node_81 [ ];
node_82 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_83 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_82 -> node_83 [ arrowhead=none, color="magenta" ];
node_84 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_82 -> node_84 [ arrowhead=none ];
node_85 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_86 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black" ];
node_85 -> node_86 [ ];
node_87 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_88 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_87 -> node_88 [ arrowhead=none, color="magenta" ];
node_89 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_87 -> node_89 [ arrowhead=none ];
node_90 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_91 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black" ];
node_90 -> node_91 [ ];
node_92 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_93 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_92 -> node_93 [ arrowhead=none, color="magenta" ];
node_94 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_92 -> node_94 [ arrowhead=none ];
node_95 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black" ];
node_92 -> node_95 [ arrowhead=none ];
node_96 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_92 -> node_96 [ arrowhead=none ];
node_90 -> node_92 [ ];
node_87 -> node_90 [ arrowhead=none ];
node_97 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_87 -> node_97 [ arrowhead=none ];
node_85 -> node_87 [ ];
node_82 -> node_85 [ arrowhead=none ];
node_98 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_82 -> node_98 [ arrowhead=none ];
node_80 -> node_82 [ ];
node_77 -> node_80 [ arrowhead=none ];
node_99 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_77 -> node_99 [ arrowhead=none ];
node_75 -> node_77 [ ];
node_72 -> node_75 [ arrowhead=none ];
node_100 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_72 -> node_100 [ arrowhead=none ];
node_70 -> node_72 [ ];
node_67 -> node_70 [ arrowhead=none ];
node_101 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_67 -> node_101 [ arrowhead=none ];
node_65 -> node_67 [ ];
node_62 -> node_65 [ arrowhead=none ];
node_102 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_62 -> node_102 [ arrowhead=none ];
node_60 -> node_62 [ ];
node_57 -> node_60 [ arrowhead=none ];
node_103 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_57 -> node_103 [ arrowhead=none ];
node_55 -> node_57 [ ];
node_52 -> node_55 [ arrowhead=none ];
node_104 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_52 -> node_104 [ arrowhead=none ];
node_50 -> node_52 [ ];
node_47 -> node_50 [ arrowhead=none ];
node_105 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_47 -> node_105 [ arrowhead=none ];
node_45 -> node_47 [ ];
node_42 -> node_45 [ arrowhead=none ];
node_106 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_42 -> node_106 [ arrowhead=none ];
node_41_42[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_41 -> node_41_42[style= invis, weight=99];
node_41_42 -> node_42[style= invis];
node_107 [ label=h, fontcolor="purple" , shape=none ];
node_41 -> node_107 [ arrowhead=none, color="purple" , weight=99];
node_108[label = maxstem0, shape="box", style=invis];
node_107 -> node_108[weight = 99, style = invis];
node_109[label = maxstem0, shape="box", style=invis];
node_108 -> node_109[weight = 99, style = invis];
node_110[label = maxstem0, shape="box", style=invis];
node_109 -> node_110[weight = 99, style = invis];
node_111[label = maxstem0, shape="box", style=invis];
node_110 -> node_111[weight = 99, style = invis];
node_112[label = maxstem0, shape="box", style=invis];
node_111 -> node_112[weight = 99, style = invis];
node_113[label = maxstem0, shape="box", style=invis];
node_112 -> node_113[weight = 99, style = invis];
node_114[label = maxstem0, shape="box", style=invis];
node_113 -> node_114[weight = 99, style = invis];
node_115[label = maxstem0, shape="box", style=invis];
node_114 -> node_115[weight = 99, style = invis];
node_116[label = maxstem0, shape="box", style=invis];
node_115 -> node_116[weight = 99, style = invis];
node_117[label = maxstem0, shape="box", style=invis];
node_116 -> node_117[weight = 99, style = invis];
node_118[label = maxstem0, shape="box", style=invis];
node_117 -> node_118[weight = 99, style = invis];
node_119[label = maxstem0, shape="box", style=invis];
node_118 -> node_119[weight = 99, style = invis];
node_120[label = maxstem0, shape="box", style=invis];
node_119 -> node_120[weight = 99, style = invis];
node_121[label = maxstem0, shape="box", style=invis];
node_120 -> node_121[weight = 99, style = invis];
node_122[label = maxstem0, shape="box", style=invis];
node_121 -> node_122[weight = 99, style = invis];
node_123[label = maxstem0, shape="box", style=invis];
node_122 -> node_123[weight = 99, style = invis];
node_124[label = maxstem0, shape="box", style=invis];
node_123 -> node_124[weight = 99, style = invis];
node_125[label = maxstem0, shape="box", style=invis];
node_124 -> node_125[weight = 99, style = invis];
node_126[label = maxstem0, shape="box", style=invis];
node_125 -> node_126[weight = 99, style = invis];
node_127[label = maxstem0, shape="box", style=invis];
node_126 -> node_127[weight = 99, style = invis];
node_128[label = maxstem0, shape="box", style=invis];
node_127 -> node_128[weight = 99, style = invis];
{ rank=same node_41 node_41_42 node_42 }
}
node_40 -> node_41 [ style = invis];
subgraph cluster_6{
node_129 [ label=<<table border='0'><tr><td>motif1</td></tr></table>>, color="black", shape="box", style="dotted" ];
node_130 [ label=<<table border='0'><tr><td>hairpin1</td></tr></table>>, color="black" ];
node_129_130[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_129 -> node_129_130[style= invis, weight=99];
node_129_130 -> node_130[style= invis];
node_131 [ label=h, fontcolor="purple" , shape=none ];
node_129 -> node_131 [ arrowhead=none, color="purple" , weight=99];
{ rank=same node_129 node_129_130 node_130 }
}
node_128 -> node_129 [ style = invis];
subgraph cluster_7{
node_132 [ label=<<table border='0'><tr><td>hairpin1</td></tr></table>>, color="black", shape="box", style="dotted" ];
node_133 [ label=<<table border='0'><tr><td>hl</td></tr></table>>, color="green" ];
node_134 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_133 -> node_134 [ arrowhead=none, color="magenta" ];
node_135 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_133 -> node_135 [ arrowhead=none ];
node_136 [ label=<<table border='0'><tr><td>REGION</td></tr></table>>, color="blue" ];
node_137 [ label="minsize(3)" , fontcolor="magenta" , shape=none ];
node_136 -> node_137 [ arrowhead=none, color="magenta" ];
node_133 -> node_136 [ arrowhead=none ];
node_138 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_133 -> node_138 [ arrowhead=none ];
node_132_133[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_132 -> node_132_133[style= invis, weight=99];
node_132_133 -> node_133[style= invis];
node_139 [ label=h, fontcolor="purple" , shape=none ];
node_132 -> node_139 [ arrowhead=none, color="purple" , weight=99];
node_140[label = hairpin1, shape="box", style=invis];
node_139 -> node_140[weight = 99, style = invis];
{ rank=same node_132 node_132_133 node_133 }
}
node_131 -> node_132 [ style = invis];
subgraph cluster_8{
node_141 [ label=<<table border='0'><tr><td>tail0</td></tr></table>>, color="black", shape="box" ];
node_142 [ label=<<table border='0'><tr><td>cadd</td></tr></table>>, color="green" ];
node_143 [ label=<<table border='0'><tr><td>motif2</td></tr></table>>, color="black" ];
node_142 -> node_143 [ arrowhead=none ];
node_144 [ label=<<table border='0'><tr><td>tail1</td></tr></table>>, color="black" ];
node_142 -> node_144 [ arrowhead=none ];
node_141_142[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_141 -> node_141_142[style= invis, weight=99];
node_141_142 -> node_142[style= invis];
node_145 [ label=h, fontcolor="purple" , shape=none ];
node_141 -> node_145 [ arrowhead=none, color="purple" , weight=99];
node_146[label = tail0, shape="box", style=invis];
node_145 -> node_146[weight = 99, style = invis];
{ rank=same node_141 node_141_142 node_142 }
}
node_140 -> node_141 [ style = invis];
subgraph cluster_9{
node_147 [ label=<<table border='0'><tr><td>motif2</td></tr></table>>, color="black", shape="box", style="dotted" ];
node_148 [ label=<<table border='0'><tr><td>ss</td></tr></table>>, color="green" ];
node_149 [ label=<<table border='0'><tr><td>UREGION</td></tr></table>>, color="blue" ];
node_148 -> node_149 [ arrowhead=none ];
node_147_148[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_147 -> node_147_148[style= invis, weight=99];
node_147_148 -> node_148[style= invis];
node_150 [ label=h, fontcolor="purple" , shape=none ];
node_147 -> node_150 [ arrowhead=none, color="purple" , weight=99];
node_151[label = motif2, shape="box", style=invis];
node_150 -> node_151[weight = 99, style = invis];
{ rank=same node_147 node_147_148 node_148 }
}
node_146 -> node_147 [ style = invis];
subgraph cluster_10{
node_152 [ label=<<table border='0'><tr><td>tail1</td></tr></table>>, color="black", shape="box" ];
node_153 [ label=<<table border='0'><tr><td>cadd</td></tr></table>>, color="green" ];
node_154 [ label=<<table border='0'><tr><td>motif3</td></tr></table>>, color="black" ];
node_153 -> node_154 [ arrowhead=none ];
node_155 [ label=<<table border='0'><tr><td>tail2</td></tr></table>>, color="black" ];
node_153 -> node_155 [ arrowhead=none ];
node_152_153[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_152 -> node_152_153[style= invis, weight=99];
node_152_153 -> node_153[style= invis];
node_156 [ label=h, fontcolor="purple" , shape=none ];
node_152 -> node_156 [ arrowhead=none, color="purple" , weight=99];
node_157[label = tail1, shape="box", style=invis];
node_156 -> node_157[weight = 99, style = invis];
{ rank=same node_152 node_152_153 node_153 }
}
node_151 -> node_152 [ style = invis];
subgraph cluster_11{
node_158 [ label=<<table border='0'><tr><td>motif3</td></tr></table>>, color="black", shape="box" ];
node_159 [ label=<<table border='0'><tr><td>dlr</td></tr></table>>, color="green" ];
node_160 [ label=<<table border='0'><tr><td>LOC</td></tr></table>>, color="blue" ];
node_159 -> node_160 [ arrowhead=none ];
node_161 [ label=<<table border='0'><tr><td>stem3</td></tr></table>>, color="black" ];
node_159 -> node_161 [ arrowhead=none ];
node_162 [ label=<<table border='0'><tr><td>LOC</td></tr></table>>, color="blue" ];
node_159 -> node_162 [ arrowhead=none ];
node_158_159[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_158 -> node_158_159[style= invis, weight=99];
node_158_159 -> node_159[style= invis];
node_163 [ label=h, fontcolor="purple" , shape=none ];
node_158 -> node_163 [ arrowhead=none, color="purple" , weight=99];
node_164[label = motif3, shape="box", style=invis];
node_163 -> node_164[weight = 99, style = invis];
{ rank=same node_158 node_158_159 node_159 }
}
node_157 -> node_158 [ style = invis];
subgraph cluster_12{
node_165 [ label=<<table border='0'><tr><td>stem3</td></tr></table>>, color="black", shape="box", style="dotted" ];
node_166 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_167 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_166 -> node_167 [ arrowhead=none, color="magenta" ];
node_168 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_166 -> node_168 [ arrowhead=none ];
node_169 [ label=<<table border='0'><tr><td>maxstem3</td></tr></table>>, color="black" ];
node_166 -> node_169 [ arrowhead=none ];
node_170 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_166 -> node_170 [ arrowhead=none ];
node_165_166[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_165 -> node_165_166[style= invis, weight=99];
node_165_166 -> node_166[style= invis];
node_171 [ label=h, fontcolor="purple" , shape=none ];
node_165 -> node_171 [ arrowhead=none, color="purple" , weight=99];
node_172[label = stem3, shape="box", style=invis];
node_171 -> node_172[weight = 99, style = invis];
{ rank=same node_165 node_165_166 node_166 }
}
node_164 -> node_165 [ style = invis];
subgraph cluster_13{
node_173 [ label=<<table border='0'><tr><td>maxstem3</td></tr></table>>, color="black", shape="box", style="dotted" ];
node_174 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_175 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_174 -> node_175 [ arrowhead=none, color="magenta" ];
node_176 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_174 -> node_176 [ arrowhead=none ];
node_177 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_178 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_177 -> node_178 [ ];
node_179 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_180 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_179 -> node_180 [ arrowhead=none, color="magenta" ];
node_181 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_179 -> node_181 [ arrowhead=none ];
node_182 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_183 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_182 -> node_183 [ ];
node_184 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_185 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_184 -> node_185 [ arrowhead=none, color="magenta" ];
node_186 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_184 -> node_186 [ arrowhead=none ];
node_187 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_188 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_187 -> node_188 [ ];
node_189 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_190 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_189 -> node_190 [ arrowhead=none, color="magenta" ];
node_191 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_189 -> node_191 [ arrowhead=none ];
node_192 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_193 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_192 -> node_193 [ ];
node_194 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_195 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_194 -> node_195 [ arrowhead=none, color="magenta" ];
node_196 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_194 -> node_196 [ arrowhead=none ];
node_197 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_198 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_197 -> node_198 [ ];
node_199 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_200 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_199 -> node_200 [ arrowhead=none, color="magenta" ];
node_201 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_199 -> node_201 [ arrowhead=none ];
node_202 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_203 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_202 -> node_203 [ ];
node_204 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_205 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_204 -> node_205 [ arrowhead=none, color="magenta" ];
node_206 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_204 -> node_206 [ arrowhead=none ];
node_207 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_208 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_207 -> node_208 [ ];
node_209 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_210 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_209 -> node_210 [ arrowhead=none, color="magenta" ];
node_211 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_209 -> node_211 [ arrowhead=none ];
node_212 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_213 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_212 -> node_213 [ ];
node_214 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_215 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_214 -> node_215 [ arrowhead=none, color="magenta" ];
node_216 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_214 -> node_216 [ arrowhead=none ];
node_217 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_218 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_217 -> node_218 [ ];
node_219 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_220 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_219 -> node_220 [ arrowhead=none, color="magenta" ];
node_221 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_219 -> node_221 [ arrowhead=none ];
node_222 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_223 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_222 -> node_223 [ ];
node_224 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_225 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_224 -> node_225 [ arrowhead=none, color="magenta" ];
node_226 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_224 -> node_226 [ arrowhead=none ];
node_227 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_228 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_227 -> node_228 [ ];
node_229 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_230 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_229 -> node_230 [ arrowhead=none, color="magenta" ];
node_231 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_229 -> node_231 [ arrowhead=none ];
node_232 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_233 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_232 -> node_233 [ ];
node_234 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_235 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_234 -> node_235 [ arrowhead=none, color="magenta" ];
node_236 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_234 -> node_236 [ arrowhead=none ];
node_237 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_238 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_237 -> node_238 [ ];
node_239 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_240 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_239 -> node_240 [ arrowhead=none, color="magenta" ];
node_241 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_239 -> node_241 [ arrowhead=none ];
node_242 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_243 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_242 -> node_243 [ ];
node_244 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_245 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_244 -> node_245 [ arrowhead=none, color="magenta" ];
node_246 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_244 -> node_246 [ arrowhead=none ];
node_247 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_248 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_247 -> node_248 [ ];
node_249 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_250 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_249 -> node_250 [ arrowhead=none, color="magenta" ];
node_251 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_249 -> node_251 [ arrowhead=none ];
node_252 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_253 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_252 -> node_253 [ ];
node_254 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_255 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_254 -> node_255 [ arrowhead=none, color="magenta" ];
node_256 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_254 -> node_256 [ arrowhead=none ];
node_257 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_258 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_257 -> node_258 [ ];
node_259 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_260 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_259 -> node_260 [ arrowhead=none, color="magenta" ];
node_261 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_259 -> node_261 [ arrowhead=none ];
node_262 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_263 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_262 -> node_263 [ ];
node_264 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_265 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_264 -> node_265 [ arrowhead=none, color="magenta" ];
node_266 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_264 -> node_266 [ arrowhead=none ];
node_267 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_268 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_267 -> node_268 [ ];
node_269 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_270 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_269 -> node_270 [ arrowhead=none, color="magenta" ];
node_271 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_269 -> node_271 [ arrowhead=none ];
node_272 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_273 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_272 -> node_273 [ ];
node_274 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_275 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_274 -> node_275 [ arrowhead=none, color="magenta" ];
node_276 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_274 -> node_276 [ arrowhead=none ];
node_277 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_278 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_277 -> node_278 [ ];
node_279 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_280 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_279 -> node_280 [ arrowhead=none, color="magenta" ];
node_281 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_279 -> node_281 [ arrowhead=none ];
node_282 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_283 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_282 -> node_283 [ ];
node_284 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_285 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_284 -> node_285 [ arrowhead=none, color="magenta" ];
node_286 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_284 -> node_286 [ arrowhead=none ];
node_287 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_288 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_287 -> node_288 [ ];
node_289 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_290 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_289 -> node_290 [ arrowhead=none, color="magenta" ];
node_291 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_289 -> node_291 [ arrowhead=none ];
node_292 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black" ];
node_289 -> node_292 [ arrowhead=none ];
node_293 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_289 -> node_293 [ arrowhead=none ];
node_287 -> node_289 [ ];
node_284 -> node_287 [ arrowhead=none ];
node_294 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_284 -> node_294 [ arrowhead=none ];
node_282 -> node_284 [ ];
node_279 -> node_282 [ arrowhead=none ];
node_295 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_279 -> node_295 [ arrowhead=none ];
node_277 -> node_279 [ ];
node_274 -> node_277 [ arrowhead=none ];
node_296 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_274 -> node_296 [ arrowhead=none ];
node_272 -> node_274 [ ];
node_269 -> node_272 [ arrowhead=none ];
node_297 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_269 -> node_297 [ arrowhead=none ];
node_267 -> node_269 [ ];
node_264 -> node_267 [ arrowhead=none ];
node_298 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_264 -> node_298 [ arrowhead=none ];
node_262 -> node_264 [ ];
node_259 -> node_262 [ arrowhead=none ];
node_299 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_259 -> node_299 [ arrowhead=none ];
node_257 -> node_259 [ ];
node_254 -> node_257 [ arrowhead=none ];
node_300 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_254 -> node_300 [ arrowhead=none ];
node_252 -> node_254 [ ];
node_249 -> node_252 [ arrowhead=none ];
node_301 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_249 -> node_301 [ arrowhead=none ];
node_247 -> node_249 [ ];
node_244 -> node_247 [ arrowhead=none ];
node_302 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_244 -> node_302 [ arrowhead=none ];
node_242 -> node_244 [ ];
node_239 -> node_242 [ arrowhead=none ];
node_303 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_239 -> node_303 [ arrowhead=none ];
node_237 -> node_239 [ ];
node_234 -> node_237 [ arrowhead=none ];
node_304 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_234 -> node_304 [ arrowhead=none ];
node_232 -> node_234 [ ];
node_229 -> node_232 [ arrowhead=none ];
node_305 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_229 -> node_305 [ arrowhead=none ];
node_227 -> node_229 [ ];
node_224 -> node_227 [ arrowhead=none ];
node_306 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_224 -> node_306 [ arrowhead=none ];
node_222 -> node_224 [ ];
node_219 -> node_222 [ arrowhead=none ];
node_307 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_219 -> node_307 [ arrowhead=none ];
node_217 -> node_219 [ ];
node_214 -> node_217 [ arrowhead=none ];
node_308 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_214 -> node_308 [ arrowhead=none ];
node_212 -> node_214 [ ];
node_209 -> node_212 [ arrowhead=none ];
node_309 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_209 -> node_309 [ arrowhead=none ];
node_207 -> node_209 [ ];
node_204 -> node_207 [ arrowhead=none ];
node_310 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_204 -> node_310 [ arrowhead=none ];
node_202 -> node_204 [ ];
node_199 -> node_202 [ arrowhead=none ];
node_311 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_199 -> node_311 [ arrowhead=none ];
node_197 -> node_199 [ ];
node_194 -> node_197 [ arrowhead=none ];
node_312 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_194 -> node_312 [ arrowhead=none ];
node_192 -> node_194 [ ];
node_189 -> node_192 [ arrowhead=none ];
node_313 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_189 -> node_313 [ arrowhead=none ];
node_187 -> node_189 [ ];
node_184 -> node_187 [ arrowhead=none ];
node_314 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_184 -> node_314 [ arrowhead=none ];
node_182 -> node_184 [ ];
node_179 -> node_182 [ arrowhead=none ];
node_315 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_179 -> node_315 [ arrowhead=none ];
node_177 -> node_179 [ ];
node_174 -> node_177 [ arrowhead=none ];
node_316 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_174 -> node_316 [ arrowhead=none ];
node_173_174[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_173 -> node_173_174[style= invis, weight=99];
node_173_174 -> node_174[style= invis];
node_317 [ label=h, fontcolor="purple" , shape=none ];
node_173 -> node_317 [ arrowhead=none, color="purple" , weight=99];
node_318[label = maxstem3, shape="box", style=invis];
node_317 -> node_318[weight = 99, style = invis];
node_319[label = maxstem3, shape="box", style=invis];
node_318 -> node_319[weight = 99, style = invis];
node_320[label = maxstem3, shape="box", style=invis];
node_319 -> node_320[weight = 99, style = invis];
node_321[label = maxstem3, shape="box", style=invis];
node_320 -> node_321[weight = 99, style = invis];
node_322[label = maxstem3, shape="box", style=invis];
node_321 -> node_322[weight = 99, style = invis];
node_323[label = maxstem3, shape="box", style=invis];
node_322 -> node_323[weight = 99, style = invis];
node_324[label = maxstem3, shape="box", style=invis];
node_323 -> node_324[weight = 99, style = invis];
node_325[label = maxstem3, shape="box", style=invis];
node_324 -> node_325[weight = 99, style = invis];
node_326[label = maxstem3, shape="box", style=invis];
node_325 -> node_326[weight = 99, style = invis];
node_327[label = maxstem3, shape="box", style=invis];
node_326 -> node_327[weight = 99, style = invis];
node_328[label = maxstem3, shape="box", style=invis];
node_327 -> node_328[weight = 99, style = invis];
node_329[label = maxstem3, shape="box", style=invis];
node_328 -> node_329[weight = 99, style = invis];
node_330[label = maxstem3, shape="box", style=invis];
node_329 -> node_330[weight = 99, style = invis];
node_331[label = maxstem3, shape="box", style=invis];
node_330 -> node_331[weight = 99, style = invis];
node_332[label = maxstem3, shape="box", style=invis];
node_331 -> node_332[weight = 99, style = invis];
node_333[label = maxstem3, shape="box", style=invis];
node_332 -> node_333[weight = 99, style = invis];
node_334[label = maxstem3, shape="box", style=invis];
node_333 -> node_334[weight = 99, style = invis];
node_335[label = maxstem3, shape="box", style=invis];
node_334 -> node_335[weight = 99, style = invis];
node_336[label = maxstem3, shape="box", style=invis];
node_335 -> node_336[weight = 99, style = invis];
node_337[label = maxstem3, shape="box", style=invis];
node_336 -> node_337[weight = 99, style = invis];
node_338[label = maxstem3, shape="box", style=invis];
node_337 -> node_338[weight = 99, style = invis];
node_339[label = maxstem3, shape="box", style=invis];
node_338 -> node_339[weight = 99, style = invis];
node_340[label = maxstem3, shape="box", style=invis];
node_339 -> node_340[weight = 99, style = invis];
node_341[label = maxstem3, shape="box", style=invis];
node_340 -> node_341[weight = 99, style = invis];
node_342[label = maxstem3, shape="box", style=invis];
node_341 -> node_342[weight = 99, style = invis];
node_343[label = maxstem3, shape="box", style=invis];
node_342 -> node_343[weight = 99, style = invis];
node_344[label = maxstem3, shape="box", style=invis];
node_343 -> node_344[weight = 99, style = invis];
node_345[label = maxstem3, shape="box", style=invis];
node_344 -> node_345[weight = 99, style = invis];
node_346[label = maxstem3, shape="box", style=invis];
node_345 -> node_346[weight = 99, style = invis];
node_347[label = maxstem3, shape="box", style=invis];
node_346 -> node_347[weight = 99, style = invis];
node_348[label = maxstem3, shape="box", style=invis];
node_347 -> node_348[weight = 99, style = invis];
node_349[label = maxstem3, shape="box", style=invis];
node_348 -> node_349[weight = 99, style = invis];
node_350[label = maxstem3, shape="box", style=invis];
node_349 -> node_350[weight = 99, style = invis];
node_351[label = maxstem3, shape="box", style=invis];
node_350 -> node_351[weight = 99, style = invis];
node_352[label = maxstem3, shape="box", style=invis];
node_351 -> node_352[weight = 99, style = invis];
node_353[label = maxstem3, shape="box", style=invis];
node_352 -> node_353[weight = 99, style = invis];
node_354[label = maxstem3, shape="box", style=invis];
node_353 -> node_354[weight = 99, style = invis];
node_355[label = maxstem3, shape="box", style=invis];
node_354 -> node_355[weight = 99, style = invis];
node_356[label = maxstem3, shape="box", style=invis];
node_355 -> node_356[weight = 99, style = invis];
node_357[label = maxstem3, shape="box", style=invis];
node_356 -> node_357[weight = 99, style = invis];
node_358[label = maxstem3, shape="box", style=invis];
node_357 -> node_358[weight = 99, style = invis];
node_359[label = maxstem3, shape="box", style=invis];
node_358 -> node_359[weight = 99, style = invis];
node_360[label = maxstem3, shape="box", style=invis];
node_359 -> node_360[weight = 99, style = invis];
node_361[label = maxstem3, shape="box", style=invis];
node_360 -> node_361[weight = 99, style = invis];
node_362[label = maxstem3, shape="box", style=invis];
node_361 -> node_362[weight = 99, style = invis];
node_363[label = maxstem3, shape="box", style=invis];
node_362 -> node_363[weight = 99, style = invis];
node_364[label = maxstem3, shape="box", style=invis];
node_363 -> node_364[weight = 99, style = invis];
{ rank=same node_173 node_173_174 node_174 }
}
node_172 -> node_173 [ style = invis];
subgraph cluster_14{
node_365 [ label=<<table border='0'><tr><td>motif4</td></tr></table>>, color="black", shape="box", style="dotted" ];
node_366 [ label=<<table border='0'><tr><td>hairpin4</td></tr></table>>, color="black" ];
node_365_366[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_365 -> node_365_366[style= invis, weight=99];
node_365_366 -> node_366[style= invis];
node_367 [ label=h, fontcolor="purple" , shape=none ];
node_365 -> node_367 [ arrowhead=none, color="purple" , weight=99];
{ rank=same node_365 node_365_366 node_366 }
}
node_364 -> node_365 [ style = invis];
subgraph cluster_15{
node_368 [ label=<<table border='0'><tr><td>hairpin4</td></tr></table>>, color="black", shape="box", style="dotted" ];
node_369 [ label=<<table border='0'><tr><td>hl</td></tr></table>>, color="green" ];
node_370 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_369 -> node_370 [ arrowhead=none, color="magenta" ];
node_371 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_369 -> node_371 [ arrowhead=none ];
node_372 [ label=<<table border='0'><tr><td>REGION</td></tr></table>>, color="blue" ];
node_373 [ label="minsize(3)" , fontcolor="magenta" , shape=none ];
node_372 -> node_373 [ arrowhead=none, color="magenta" ];
node_369 -> node_372 [ arrowhead=none ];
node_374 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_369 -> node_374 [ arrowhead=none ];
node_368_369[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_368 -> node_368_369[style= invis, weight=99];
node_368_369 -> node_369[style= invis];
node_375 [ label=h, fontcolor="purple" , shape=none ];
node_368 -> node_375 [ arrowhead=none, color="purple" , weight=99];
node_376[label = hairpin4, shape="box", style=invis];
node_375 -> node_376[weight = 99, style = invis];
{ rank=same node_368 node_368_369 node_369 }
}
node_367 -> node_368 [ style = invis];
subgraph cluster_16{
node_377 [ label=<<table border='0'><tr><td>tail2</td></tr></table>>, color="black", shape="box" ];
node_378 [ label=<<table border='0'><tr><td>cadd</td></tr></table>>, color="green" ];
node_379 [ label=<<table border='0'><tr><td>motif5</td></tr></table>>, color="black" ];
node_378 -> node_379 [ arrowhead=none ];
node_380 [ label=<<table border='0'><tr><td>tail3</td></tr></table>>, color="black" ];
node_378 -> node_380 [ arrowhead=none ];
node_377_378[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_377 -> node_377_378[style= invis, weight=99];
node_377_378 -> node_378[style= invis];
node_381 [ label=h, fontcolor="purple" , shape=none ];
node_377 -> node_381 [ arrowhead=none, color="purple" , weight=99];
node_382[label = tail2, shape="box", style=invis];
node_381 -> node_382[weight = 99, style = invis];
{ rank=same node_377 node_377_378 node_378 }
}
node_376 -> node_377 [ style = invis];
subgraph cluster_17{
node_383 [ label=<<table border='0'><tr><td>motif5</td></tr></table>>, color="black", shape="box" ];
node_384 [ label=<<table border='0'><tr><td>ss</td></tr></table>>, color="green" ];
node_385 [ label=<<table border='0'><tr><td>UREGION</td></tr></table>>, color="blue" ];
node_384 -> node_385 [ arrowhead=none ];
node_383_384[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_383 -> node_383_384[style= invis, weight=99];
node_383_384 -> node_384[style= invis];
node_386 [ label=h, fontcolor="purple" , shape=none ];
node_383 -> node_386 [ arrowhead=none, color="purple" , weight=99];
node_387[label = motif5, shape="box", style=invis];
node_386 -> node_387[weight = 99, style = invis];
{ rank=same node_383 node_383_384 node_384 }
}
node_382 -> node_383 [ style = invis];
subgraph cluster_18{
node_388 [ label=<<table border='0'><tr><td>tail3</td></tr></table>>, color="black", shape="box" ];
node_389 [ label=<<table border='0'><tr><td>motif6</td></tr></table>>, color="black" ];
node_388_389[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_388 -> node_388_389[style= invis, weight=99];
node_388_389 -> node_389[style= invis];
node_390 [ label=h_388, fontcolor="purple" , shape=none , style=invis];
node_388 -> node_390 [ arrowhead=none, color="purple" , style=invis, weight=99];
{ rank=same node_388 node_388_389 node_389 }
}
node_387 -> node_388 [ style = invis];
subgraph cluster_19{
node_391 [ label=<<table border='0'><tr><td>motif6</td></tr></table>>, color="black", shape="box", style="dotted" ];
node_392 [ label=<<table border='0'><tr><td>dlr</td></tr></table>>, color="green" ];
node_393 [ label=<<table border='0'><tr><td>LOC</td></tr></table>>, color="blue" ];
node_392 -> node_393 [ arrowhead=none ];
node_394 [ label=<<table border='0'><tr><td>stem6</td></tr></table>>, color="black" ];
node_392 -> node_394 [ arrowhead=none ];
node_395 [ label=<<table border='0'><tr><td>LOC</td></tr></table>>, color="blue" ];
node_392 -> node_395 [ arrowhead=none ];
node_391_392[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_391 -> node_391_392[style= invis, weight=99];
node_391_392 -> node_392[style= invis];
node_396 [ label=h, fontcolor="purple" , shape=none ];
node_391 -> node_396 [ arrowhead=none, color="purple" , weight=99];
node_397[label = motif6, shape="box", style=invis];
node_396 -> node_397[weight = 99, style = invis];
{ rank=same node_391 node_391_392 node_392 }
}
node_390 -> node_391 [ style = invis];
subgraph cluster_20{
node_398 [ label=<<table border='0'><tr><td>stem6</td></tr></table>>, color="black", shape="box", style="dotted" ];
node_399 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_400 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_399 -> node_400 [ arrowhead=none, color="magenta" ];
node_401 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_399 -> node_401 [ arrowhead=none ];
node_402 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_403 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_402 -> node_403 [ arrowhead=none, color="magenta" ];
node_404 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_402 -> node_404 [ arrowhead=none ];
node_405 [ label=<<table border='0'><tr><td>maxstem6</td></tr></table>>, color="black" ];
node_402 -> node_405 [ arrowhead=none ];
node_406 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_402 -> node_406 [ arrowhead=none ];
node_399 -> node_402 [ arrowhead=none ];
node_407 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_399 -> node_407 [ arrowhead=none ];
node_398_399[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_398 -> node_398_399[style= invis, weight=99];
node_398_399 -> node_399[style= invis];
node_408 [ label=h, fontcolor="purple" , shape=none ];
node_398 -> node_408 [ arrowhead=none, color="purple" , weight=99];
node_409[label = stem6, shape="box", style=invis];
node_408 -> node_409[weight = 99, style = invis];
node_410[label = stem6, shape="box", style=invis];
node_409 -> node_410[weight = 99, style = invis];
{ rank=same node_398 node_398_399 node_399 }
}
node_397 -> node_398 [ style = invis];
subgraph cluster_21{
node_411 [ label=<<table border='0'><tr><td>maxstem6</td></tr></table>>, color="black", shape="box", style="dotted" ];
node_412 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_413 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_412 -> node_413 [ arrowhead=none, color="magenta" ];
node_414 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_412 -> node_414 [ arrowhead=none ];
node_415 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_416 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_415 -> node_416 [ ];
node_417 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_418 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_417 -> node_418 [ arrowhead=none, color="magenta" ];
node_419 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_417 -> node_419 [ arrowhead=none ];
node_420 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_421 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_420 -> node_421 [ ];
node_422 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_423 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_422 -> node_423 [ arrowhead=none, color="magenta" ];
node_424 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_422 -> node_424 [ arrowhead=none ];
node_425 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_426 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_425 -> node_426 [ ];
node_427 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_428 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_427 -> node_428 [ arrowhead=none, color="magenta" ];
node_429 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_427 -> node_429 [ arrowhead=none ];
node_430 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_431 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_430 -> node_431 [ ];
node_432 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_433 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_432 -> node_433 [ arrowhead=none, color="magenta" ];
node_434 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_432 -> node_434 [ arrowhead=none ];
node_435 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_436 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_435 -> node_436 [ ];
node_437 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_438 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_437 -> node_438 [ arrowhead=none, color="magenta" ];
node_439 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_437 -> node_439 [ arrowhead=none ];
node_440 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_441 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_440 -> node_441 [ ];
node_442 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_443 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_442 -> node_443 [ arrowhead=none, color="magenta" ];
node_444 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_442 -> node_444 [ arrowhead=none ];
node_445 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_446 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_445 -> node_446 [ ];
node_447 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_448 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_447 -> node_448 [ arrowhead=none, color="magenta" ];
node_449 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_447 -> node_449 [ arrowhead=none ];
node_450 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_451 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_450 -> node_451 [ ];
node_452 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_453 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_452 -> node_453 [ arrowhead=none, color="magenta" ];
node_454 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_452 -> node_454 [ arrowhead=none ];
node_455 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_456 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_455 -> node_456 [ ];
node_457 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_458 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_457 -> node_458 [ arrowhead=none, color="magenta" ];
node_459 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_457 -> node_459 [ arrowhead=none ];
node_460 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_461 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_460 -> node_461 [ ];
node_462 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_463 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_462 -> node_463 [ arrowhead=none, color="magenta" ];
node_464 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_462 -> node_464 [ arrowhead=none ];
node_465 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_466 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_465 -> node_466 [ ];
node_467 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_468 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_467 -> node_468 [ arrowhead=none, color="magenta" ];
node_469 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_467 -> node_469 [ arrowhead=none ];
node_470 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_471 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_470 -> node_471 [ ];
node_472 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_473 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_472 -> node_473 [ arrowhead=none, color="magenta" ];
node_474 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_472 -> node_474 [ arrowhead=none ];
node_475 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_476 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_475 -> node_476 [ ];
node_477 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_478 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_477 -> node_478 [ arrowhead=none, color="magenta" ];
node_479 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_477 -> node_479 [ arrowhead=none ];
node_480 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_481 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_480 -> node_481 [ ];
node_482 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_483 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_482 -> node_483 [ arrowhead=none, color="magenta" ];
node_484 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_482 -> node_484 [ arrowhead=none ];
node_485 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_486 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_485 -> node_486 [ ];
node_487 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_488 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_487 -> node_488 [ arrowhead=none, color="magenta" ];
node_489 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_487 -> node_489 [ arrowhead=none ];
node_490 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_491 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_490 -> node_491 [ ];
node_492 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_493 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_492 -> node_493 [ arrowhead=none, color="magenta" ];
node_494 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_492 -> node_494 [ arrowhead=none ];
node_495 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_496 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_495 -> node_496 [ ];
node_497 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_498 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_497 -> node_498 [ arrowhead=none, color="magenta" ];
node_499 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_497 -> node_499 [ arrowhead=none ];
node_500 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_501 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_500 -> node_501 [ ];
node_502 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_503 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_502 -> node_503 [ arrowhead=none, color="magenta" ];
node_504 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_502 -> node_504 [ arrowhead=none ];
node_505 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_506 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_505 -> node_506 [ ];
node_507 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_508 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_507 -> node_508 [ arrowhead=none, color="magenta" ];
node_509 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_507 -> node_509 [ arrowhead=none ];
node_510 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_511 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_510 -> node_511 [ ];
node_512 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_513 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_512 -> node_513 [ arrowhead=none, color="magenta" ];
node_514 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_512 -> node_514 [ arrowhead=none ];
node_515 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_516 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_515 -> node_516 [ ];
node_517 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_518 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_517 -> node_518 [ arrowhead=none, color="magenta" ];
node_519 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_517 -> node_519 [ arrowhead=none ];
node_520 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_521 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_520 -> node_521 [ ];
node_522 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_523 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_522 -> node_523 [ arrowhead=none, color="magenta" ];
node_524 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_522 -> node_524 [ arrowhead=none ];
node_525 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_526 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_525 -> node_526 [ ];
node_527 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_528 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_527 -> node_528 [ arrowhead=none, color="magenta" ];
node_529 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_527 -> node_529 [ arrowhead=none ];
node_530 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_531 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_530 -> node_531 [ ];
node_532 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_533 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_532 -> node_533 [ arrowhead=none, color="magenta" ];
node_534 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_532 -> node_534 [ arrowhead=none ];
node_535 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_536 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_535 -> node_536 [ ];
node_537 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_538 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_537 -> node_538 [ arrowhead=none, color="magenta" ];
node_539 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_537 -> node_539 [ arrowhead=none ];
node_540 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_541 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_540 -> node_541 [ ];
node_542 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_543 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_542 -> node_543 [ arrowhead=none, color="magenta" ];
node_544 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_542 -> node_544 [ arrowhead=none ];
node_545 [ label=<<table border='0'><tr><td>a block</td></tr></table>>, color="gray" ];
node_546 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_545 -> node_546 [ ];
node_547 [ label=<<table border='0'><tr><td>sr</td></tr></table>>, color="green" ];
node_548 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_547 -> node_548 [ arrowhead=none, color="magenta" ];
node_549 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_547 -> node_549 [ arrowhead=none ];
node_550 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black" ];
node_547 -> node_550 [ arrowhead=none ];
node_551 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_547 -> node_551 [ arrowhead=none ];
node_545 -> node_547 [ ];
node_542 -> node_545 [ arrowhead=none ];
node_552 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_542 -> node_552 [ arrowhead=none ];
node_540 -> node_542 [ ];
node_537 -> node_540 [ arrowhead=none ];
node_553 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_537 -> node_553 [ arrowhead=none ];
node_535 -> node_537 [ ];
node_532 -> node_535 [ arrowhead=none ];
node_554 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_532 -> node_554 [ arrowhead=none ];
node_530 -> node_532 [ ];
node_527 -> node_530 [ arrowhead=none ];
node_555 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_527 -> node_555 [ arrowhead=none ];
node_525 -> node_527 [ ];
node_522 -> node_525 [ arrowhead=none ];
node_556 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_522 -> node_556 [ arrowhead=none ];
node_520 -> node_522 [ ];
node_517 -> node_520 [ arrowhead=none ];
node_557 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_517 -> node_557 [ arrowhead=none ];
node_515 -> node_517 [ ];
node_512 -> node_515 [ arrowhead=none ];
node_558 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_512 -> node_558 [ arrowhead=none ];
node_510 -> node_512 [ ];
node_507 -> node_510 [ arrowhead=none ];
node_559 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_507 -> node_559 [ arrowhead=none ];
node_505 -> node_507 [ ];
node_502 -> node_505 [ arrowhead=none ];
node_560 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_502 -> node_560 [ arrowhead=none ];
node_500 -> node_502 [ ];
node_497 -> node_500 [ arrowhead=none ];
node_561 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_497 -> node_561 [ arrowhead=none ];
node_495 -> node_497 [ ];
node_492 -> node_495 [ arrowhead=none ];
node_562 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_492 -> node_562 [ arrowhead=none ];
node_490 -> node_492 [ ];
node_487 -> node_490 [ arrowhead=none ];
node_563 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_487 -> node_563 [ arrowhead=none ];
node_485 -> node_487 [ ];
node_482 -> node_485 [ arrowhead=none ];
node_564 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_482 -> node_564 [ arrowhead=none ];
node_480 -> node_482 [ ];
node_477 -> node_480 [ arrowhead=none ];
node_565 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_477 -> node_565 [ arrowhead=none ];
node_475 -> node_477 [ ];
node_472 -> node_475 [ arrowhead=none ];
node_566 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_472 -> node_566 [ arrowhead=none ];
node_470 -> node_472 [ ];
node_467 -> node_470 [ arrowhead=none ];
node_567 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_467 -> node_567 [ arrowhead=none ];
node_465 -> node_467 [ ];
node_462 -> node_465 [ arrowhead=none ];
node_568 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_462 -> node_568 [ arrowhead=none ];
node_460 -> node_462 [ ];
node_457 -> node_460 [ arrowhead=none ];
node_569 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_457 -> node_569 [ arrowhead=none ];
node_455 -> node_457 [ ];
node_452 -> node_455 [ arrowhead=none ];
node_570 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_452 -> node_570 [ arrowhead=none ];
node_450 -> node_452 [ ];
node_447 -> node_450 [ arrowhead=none ];
node_571 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_447 -> node_571 [ arrowhead=none ];
node_445 -> node_447 [ ];
node_442 -> node_445 [ arrowhead=none ];
node_572 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_442 -> node_572 [ arrowhead=none ];
node_440 -> node_442 [ ];
node_437 -> node_440 [ arrowhead=none ];
node_573 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_437 -> node_573 [ arrowhead=none ];
node_435 -> node_437 [ ];
node_432 -> node_435 [ arrowhead=none ];
node_574 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_432 -> node_574 [ arrowhead=none ];
node_430 -> node_432 [ ];
node_427 -> node_430 [ arrowhead=none ];
node_575 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_427 -> node_575 [ arrowhead=none ];
node_425 -> node_427 [ ];
node_422 -> node_425 [ arrowhead=none ];
node_576 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_422 -> node_576 [ arrowhead=none ];
node_420 -> node_422 [ ];
node_417 -> node_420 [ arrowhead=none ];
node_577 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_417 -> node_577 [ arrowhead=none ];
node_415 -> node_417 [ ];
node_412 -> node_415 [ arrowhead=none ];
node_578 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_412 -> node_578 [ arrowhead=none ];
node_411_412[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_411 -> node_411_412[style= invis, weight=99];
node_411_412 -> node_412[style= invis];
node_579 [ label=h, fontcolor="purple" , shape=none ];
node_411 -> node_579 [ arrowhead=none, color="purple" , weight=99];
node_580[label = maxstem6, shape="box", style=invis];
node_579 -> node_580[weight = 99, style = invis];
node_581[label = maxstem6, shape="box", style=invis];
node_580 -> node_581[weight = 99, style = invis];
node_582[label = maxstem6, shape="box", style=invis];
node_581 -> node_582[weight = 99, style = invis];
node_583[label = maxstem6, shape="box", style=invis];
node_582 -> node_583[weight = 99, style = invis];
node_584[label = maxstem6, shape="box", style=invis];
node_583 -> node_584[weight = 99, style = invis];
node_585[label = maxstem6, shape="box", style=invis];
node_584 -> node_585[weight = 99, style = invis];
node_586[label = maxstem6, shape="box", style=invis];
node_585 -> node_586[weight = 99, style = invis];
node_587[label = maxstem6, shape="box", style=invis];
node_586 -> node_587[weight = 99, style = invis];
node_588[label = maxstem6, shape="box", style=invis];
node_587 -> node_588[weight = 99, style = invis];
node_589[label = maxstem6, shape="box", style=invis];
node_588 -> node_589[weight = 99, style = invis];
node_590[label = maxstem6, shape="box", style=invis];
node_589 -> node_590[weight = 99, style = invis];
node_591[label = maxstem6, shape="box", style=invis];
node_590 -> node_591[weight = 99, style = invis];
node_592[label = maxstem6, shape="box", style=invis];
node_591 -> node_592[weight = 99, style = invis];
node_593[label = maxstem6, shape="box", style=invis];
node_592 -> node_593[weight = 99, style = invis];
node_594[label = maxstem6, shape="box", style=invis];
node_593 -> node_594[weight = 99, style = invis];
node_595[label = maxstem6, shape="box", style=invis];
node_594 -> node_595[weight = 99, style = invis];
node_596[label = maxstem6, shape="box", style=invis];
node_595 -> node_596[weight = 99, style = invis];
node_597[label = maxstem6, shape="box", style=invis];
node_596 -> node_597[weight = 99, style = invis];
node_598[label = maxstem6, shape="box", style=invis];
node_597 -> node_598[weight = 99, style = invis];
node_599[label = maxstem6, shape="box", style=invis];
node_598 -> node_599[weight = 99, style = invis];
node_600[label = maxstem6, shape="box", style=invis];
node_599 -> node_600[weight = 99, style = invis];
node_601[label = maxstem6, shape="box", style=invis];
node_600 -> node_601[weight = 99, style = invis];
node_602[label = maxstem6, shape="box", style=invis];
node_601 -> node_602[weight = 99, style = invis];
node_603[label = maxstem6, shape="box", style=invis];
node_602 -> node_603[weight = 99, style = invis];
node_604[label = maxstem6, shape="box", style=invis];
node_603 -> node_604[weight = 99, style = invis];
node_605[label = maxstem6, shape="box", style=invis];
node_604 -> node_605[weight = 99, style = invis];
node_606[label = maxstem6, shape="box", style=invis];
node_605 -> node_606[weight = 99, style = invis];
node_607[label = maxstem6, shape="box", style=invis];
node_606 -> node_607[weight = 99, style = invis];
node_608[label = maxstem6, shape="box", style=invis];
node_607 -> node_608[weight = 99, style = invis];
node_609[label = maxstem6, shape="box", style=invis];
node_608 -> node_609[weight = 99, style = invis];
node_610[label = maxstem6, shape="box", style=invis];
node_609 -> node_610[weight = 99, style = invis];
node_611[label = maxstem6, shape="box", style=invis];
node_610 -> node_611[weight = 99, style = invis];
node_612[label = maxstem6, shape="box", style=invis];
node_611 -> node_612[weight = 99, style = invis];
node_613[label = maxstem6, shape="box", style=invis];
node_612 -> node_613[weight = 99, style = invis];
node_614[label = maxstem6, shape="box", style=invis];
node_613 -> node_614[weight = 99, style = invis];
node_615[label = maxstem6, shape="box", style=invis];
node_614 -> node_615[weight = 99, style = invis];
node_616[label = maxstem6, shape="box", style=invis];
node_615 -> node_616[weight = 99, style = invis];
node_617[label = maxstem6, shape="box", style=invis];
node_616 -> node_617[weight = 99, style = invis];
node_618[label = maxstem6, shape="box", style=invis];
node_617 -> node_618[weight = 99, style = invis];
node_619[label = maxstem6, shape="box", style=invis];
node_618 -> node_619[weight = 99, style = invis];
node_620[label = maxstem6, shape="box", style=invis];
node_619 -> node_620[weight = 99, style = invis];
node_621[label = maxstem6, shape="box", style=invis];
node_620 -> node_621[weight = 99, style = invis];
node_622[label = maxstem6, shape="box", style=invis];
node_621 -> node_622[weight = 99, style = invis];
node_623[label = maxstem6, shape="box", style=invis];
node_622 -> node_623[weight = 99, style = invis];
node_624[label = maxstem6, shape="box", style=invis];
node_623 -> node_624[weight = 99, style = invis];
node_625[label = maxstem6, shape="box", style=invis];
node_624 -> node_625[weight = 99, style = invis];
node_626[label = maxstem6, shape="box", style=invis];
node_625 -> node_626[weight = 99, style = invis];
node_627[label = maxstem6, shape="box", style=invis];
node_626 -> node_627[weight = 99, style = invis];
node_628[label = maxstem6, shape="box", style=invis];
node_627 -> node_628[weight = 99, style = invis];
node_629[label = maxstem6, shape="box", style=invis];
node_628 -> node_629[weight = 99, style = invis];
node_630[label = maxstem6, shape="box", style=invis];
node_629 -> node_630[weight = 99, style = invis];
node_631[label = maxstem6, shape="box", style=invis];
node_630 -> node_631[weight = 99, style = invis];
node_632[label = maxstem6, shape="box", style=invis];
node_631 -> node_632[weight = 99, style = invis];
node_633[label = maxstem6, shape="box", style=invis];
node_632 -> node_633[weight = 99, style = invis];
node_634[label = maxstem6, shape="box", style=invis];
node_633 -> node_634[weight = 99, style = invis];
{ rank=same node_411 node_411_412 node_412 }
}
node_410 -> node_411 [ style = invis];
subgraph cluster_22{
node_635 [ label=<<table border='0'><tr><td>motif7</td></tr></table>>, color="black", shape="box", style="dotted" ];
node_636 [ label=<<table border='0'><tr><td>hairpin7</td></tr></table>>, color="black" ];
node_635_636[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_635 -> node_635_636[style= invis, weight=99];
node_635_636 -> node_636[style= invis];
node_637 [ label=h, fontcolor="purple" , shape=none ];
node_635 -> node_637 [ arrowhead=none, color="purple" , weight=99];
{ rank=same node_635 node_635_636 node_636 }
}
node_634 -> node_635 [ style = invis];
subgraph cluster_23{
node_638 [ label=<<table border='0'><tr><td>hairpin7</td></tr></table>>, color="black", shape="box", style="dotted" ];
node_639 [ label=<<table border='0'><tr><td>hl</td></tr></table>>, color="green" ];
node_640 [ label="basepairing" , fontcolor="magenta" , shape=none ];
node_639 -> node_640 [ arrowhead=none, color="magenta" ];
node_641 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_639 -> node_641 [ arrowhead=none ];
node_642 [ label=<<table border='0'><tr><td>REGION</td></tr></table>>, color="blue" ];
node_643 [ label="minsize(3)" , fontcolor="magenta" , shape=none ];
node_642 -> node_643 [ arrowhead=none, color="magenta" ];
node_639 -> node_642 [ arrowhead=none ];
node_644 [ label=<<table border='0'><tr><td>BASE</td></tr></table>>, color="blue" ];
node_639 -> node_644 [ arrowhead=none ];
node_638_639[ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext];
node_638 -> node_638_639[style= invis, weight=99];
node_638_639 -> node_639[style= invis];
node_645 [ label=h, fontcolor="purple" , shape=none ];
node_638 -> node_645 [ arrowhead=none, color="purple" , weight=99];
node_646[label = hairpin7, shape="box", style=invis];
node_645 -> node_646[weight = 99, style = invis];
{ rank=same node_638 node_638_639 node_639 }
}
node_637 -> node_638 [ style = invis];
}
