digraph gra_elmamun {
compound = True;
newrank = True;
ordering = out;
subgraph cluster_1 {
    node_1 [ label=<<table border='0'><tr><td>formula</td></tr></table>>, color="black", shape="box", style="dotted" ];
    node_1 -> node_2 [ style=invis, weight=99 ];
    node_2 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_2 -> node_3 [ style=invis ];
    node_3 [ label=<<table border='0'><tr><td>number</td></tr></table>>, color="green" ];
    node_4 [ label=<<table border='0'><tr><td>INT</td></tr></table>>, color="blue" ];
    node_3 -> node_4 [ arrowhead=none ];
    node_3 -> node_5 [ style=invis ];
    node_5 [ label=<<table border='0'><tr><td><font point-size='30'>|</font></td></tr></table>>, shape=plaintext ];
    node_5 -> node_6 [ style=invis ];
    node_6 [ label=<<table border='0'><tr><td>add</td></tr></table>>, color="green" ];
    node_7 [ label=<<table border='0'><tr><td>formula</td></tr></table>>, color="black" ];
    node_6 -> node_7 [ arrowhead=none ];
    node_8 [ label=<<table border='0'><tr><td>CHAR('+')</td></tr></table>>, color="blue" ];
    node_6 -> node_8 [ arrowhead=none ];
    node_9 [ label=<<table border='0'><tr><td>formula</td></tr></table>>, color="black" ];
    node_6 -> node_9 [ arrowhead=none ];
    node_6 -> node_10 [ style=invis ];
    node_10 [ label=<<table border='0'><tr><td><font point-size='30'>|</font></td></tr></table>>, shape=plaintext ];
    node_10 -> node_11 [ style=invis ];
    node_11 [ label=<<table border='0'><tr><td>mult</td></tr></table>>, color="green" ];
    node_12 [ label=<<table border='0'><tr><td>formula</td></tr></table>>, color="black" ];
    node_11 -> node_12 [ arrowhead=none ];
    node_13 [ label=<<table border='0'><tr><td>CHAR('*')</td></tr></table>>, color="blue" ];
    node_11 -> node_13 [ arrowhead=none ];
    node_14 [ label=<<table border='0'><tr><td>formula</td></tr></table>>, color="black" ];
    node_11 -> node_14 [ arrowhead=none ];
    node_11 -> node_15 [ style=invis ];
    node_15 [ label=<<table border='0'><tr><td><font point-size='30'>|</font></td></tr></table>>, shape=plaintext ];
    node_15 -> node_16 [ style=invis ];
    node_16 [ label=<<table border='0'><tr><td>nil</td></tr></table>>, color="green" ];
    node_17 [ label=<<table border='0'><tr><td>EMPTY</td></tr></table>>, color="blue" ];
    node_16 -> node_17 [ arrowhead=none ];
    node_18 [ label=<h>, fontcolor="purple", shape=none ];
    node_1 -> node_18 [ arrowhead=none, color="purple", weight=99 ];
    { rank=same node_1 node_2 node_3 node_5 node_6 node_10 node_11 node_15 node_16 }
}
node_18 -> node_19 [ style=invis ];
subgraph cluster_2 {
    node_19 [ label=<<table border='0'><tr><td>outside_formula</td></tr></table>>, color="black", shape="box", penwidth=3, style="dotted" ];
    node_19 -> node_20 [ style=invis, weight=99 ];
    node_20 [ label=<<table border='0'><tr><td><font point-size='30'>&rarr;</font></td></tr></table>>, shape=plaintext ];
    node_20 -> node_21 [ style=invis ];
    node_21 [ label=<<table border='0'><tr><td>add</td></tr></table>>, color="green" ];
    node_22 [ label=<<table border='0'><tr><td>outside_formula</td></tr></table>>, color="black" ];
    node_21 -> node_22 [ arrowhead=none ];
    node_23 [ label=<<table border='0'><tr><td>CHAR('+')</td></tr></table>>, color="blue" ];
    node_21 -> node_23 [ arrowhead=none ];
    node_24 [ label=<<table border='0'><tr><td>formula</td></tr></table>>, color="black" ];
    node_21 -> node_24 [ arrowhead=none ];
    node_21 -> node_25 [ style=invis ];
    node_25 [ label=<<table border='0'><tr><td><font point-size='30'>|</font></td></tr></table>>, shape=plaintext ];
    node_25 -> node_26 [ style=invis ];
    node_26 [ label=<<table border='0'><tr><td>add</td></tr></table>>, color="green" ];
    node_27 [ label=<<table border='0'><tr><td>formula</td></tr></table>>, color="black" ];
    node_26 -> node_27 [ arrowhead=none ];
    node_28 [ label=<<table border='0'><tr><td>CHAR('+')</td></tr></table>>, color="blue" ];
    node_26 -> node_28 [ arrowhead=none ];
    node_29 [ label=<<table border='0'><tr><td>outside_formula</td></tr></table>>, color="black" ];
    node_26 -> node_29 [ arrowhead=none ];
    node_26 -> node_30 [ style=invis ];
    node_30 [ label=<<table border='0'><tr><td><font point-size='30'>|</font></td></tr></table>>, shape=plaintext ];
    node_30 -> node_31 [ style=invis ];
    node_31 [ label=<<table border='0'><tr><td>mult</td></tr></table>>, color="green" ];
    node_32 [ label=<<table border='0'><tr><td>outside_formula</td></tr></table>>, color="black" ];
    node_31 -> node_32 [ arrowhead=none ];
    node_33 [ label=<<table border='0'><tr><td>CHAR('*')</td></tr></table>>, color="blue" ];
    node_31 -> node_33 [ arrowhead=none ];
    node_34 [ label=<<table border='0'><tr><td>formula</td></tr></table>>, color="black" ];
    node_31 -> node_34 [ arrowhead=none ];
    node_31 -> node_35 [ style=invis ];
    node_35 [ label=<<table border='0'><tr><td><font point-size='30'>|</font></td></tr></table>>, shape=plaintext ];
    node_35 -> node_36 [ style=invis ];
    node_36 [ label=<<table border='0'><tr><td>mult</td></tr></table>>, color="green" ];
    node_37 [ label=<<table border='0'><tr><td>formula</td></tr></table>>, color="black" ];
    node_36 -> node_37 [ arrowhead=none ];
    node_38 [ label=<<table border='0'><tr><td>CHAR('*')</td></tr></table>>, color="blue" ];
    node_36 -> node_38 [ arrowhead=none ];
    node_39 [ label=<<table border='0'><tr><td>outside_formula</td></tr></table>>, color="black" ];
    node_36 -> node_39 [ arrowhead=none ];
    node_36 -> node_40 [ style=invis ];
    node_40 [ label=<<table border='0'><tr><td><font point-size='30'>|</font></td></tr></table>>, shape=plaintext ];
    node_40 -> node_41 [ style=invis ];
    node_41 [ label=<<table border='0'><tr><td>formula</td></tr></table>>, color="black" ];
    node_42 [ label="complete_track" , fontcolor="magenta" , shape=none ];
    node_41 -> node_42 [ arrowhead=none, color="magenta" ];
    node_43 [ label=<h>, fontcolor="purple", shape=none ];
    node_19 -> node_43 [ arrowhead=none, color="purple", weight=99 ];
    { rank=same node_19 node_20 node_21 node_25 node_26 node_30 node_31 node_35 node_36 node_40 node_41 }
}
}
