struct {(14, n)}
left_unpaired__LJLJ {(16, n)}
left_dangle__LJLJ {(15, n)}
noleft_dangle__LJLJ {(14, n)}
edanglel__LJ {(8, n)}
edangler__LJ {(8, n)}
edanglelr__LJ {(9, n)}
nodangle__LJ {(7, n)}
motif__LJ {(7, n)}
stack__LJ {(9, n)}
hairpin__LJ {(7, n)}
leftB__LJ {(12, n)}
rightB__LJ {(12, n)}
iloop__LJ {(13, n)}
left_unpairedEnd {(1, n)}
left_unpaired__LJ {(9, n)}
left_dangle__LJ {(8, n)}
noleft_dangle__LJ {(7, n)}
