struct 0
left_unpaired__LJLJ 2
left_dangle__LJLJ 0
noleft_dangle__LJLJ 0
edanglel__LJ 0
edangler__LJ 0
edanglelr__LJ 0
nodangle__LJ 0
motif__LJ 60
stack__LJ 1
hairpin__LJ 0
leftB__LJ 1
rightB__LJ 1
iloop__LJ 1
left_unpairedEnd 8
left_unpaired__LJ 5
left_dangle__LJ 0
noleft_dangle__LJ 0
