struct {(0, n)}
dangle_Pr {(3, n)}
dangle {(7, n)}
dangleknot {(3, n)}
closed {(7, n)}
stack {(9, n)}
hairpin {(7, n)}
leftB {(12, n)}
rightB {(12, n)}
iloop {(13, n)}
multiloop {(7, n)}
ml_comps1 {(3, n)}
ml_comps {(3, n)}
mldangle {(3, n)}
knot {(3, n)}
help_pknot {(3, n)}
front {(0, n)}
front_Pr {(0, n)}
middle {(0, n)}
mid {(1, n)}
back {(0, n)}
back_Pr {(0, n)}
pk_comps {(3, n)}
singlestrand {(1, n)}
emptystrand {(0, n)}
